"""Generated by tools/sync_locales.py; edit HA translation JSON instead."""

ERRORS = {
    "en": {
        "migration_prepare_source_invalid": "The source exports or additional IDs "
        "are invalid, unsupported or oversized. "
        "Obtain corrected coherent exports; no "
        "copy was written.",
        "migration_prepare_selection_invalid": "Choose an allowed participant, "
        "complete reviewer set or valid "
        "bounded file for this page. No "
        "association was advanced.",
        "migration_prepare_policy_changed": "The declared old reviewer set differs "
        "from the destination parents. Discard "
        "this review and reconcile the source "
        "policy and target roles; do not omit "
        "reviewers to bypass this check.",
        "migration_copy_bundle_invalid": "Invalid, incomplete or oversized bundle. "
        "Upload a corrected ZIP using the "
        "documented format; the source was not "
        "changed.",
        "migration_copy_source_unsettled": "The source has unmatched task/alarm "
        "penalties or unfinished score "
        "corrections. No copy was written. "
        "Reconcile the original records, then "
        "prepare and review a fresh coherent "
        "export; do not remove history to bypass "
        "this check.",
        "migration_copy_primary_owner_required": "Use the original household owner "
        "account, also an active Home "
        "Assistant administrator.",
        "migration_copy_confirmation_required": "Confirm exactly the page or "
        "fingerprint currently displayed.",
        "migration_copy_busy": "Another review is active. Finish it or wait for its "
        "15-minute window to expire.",
        "migration_copy_review_changed": "The owner, members, runtime or review "
        "window changed. Review again; for retries "
        "use the same archive and copy name.",
        "migration_copy_conversion_required": "Records, reviewer rights or "
        "historical photos need correction. "
        "No partial copy was created.",
        "migration_copy_retry_required": "Could not confirm the result. Retry this "
        "same reviewed action. After a restart, "
        "use the same archive and copy name; do "
        "not invent another target.",
        "migration_copy_not_loaded": "The sealed copy is registered but not loaded. "
        "Inspect its integration status; it was not "
        "force-started.",
        "migration_copy_no_pending": "No indexed copy attempts belong to this "
        "household. Older attempts require their "
        "original bundle.",
        "migration_copy_partial_bundle_required": "The saved copy is incomplete. "
        "Use the original ZIP and copy "
        "name for the reviewed recovery "
        "path.",
        "migration_copy_incompatible_bundle_required": "Saved data, participants or "
        "settings no longer match. "
        "Direct resume is blocked; "
        "inspect the original bundle "
        "and reviewed target before "
        "retrying.",
        "migration_copy_index_invalid": "The private copy index could not be "
        "verified. Nothing was reset or removed.",
        "migration_copy_index_full": "The private copy index has reached its "
        "16-attempt limit. Existing attempts are "
        "retained; no automatic eviction is performed.",
        "migration_copy_finished": "Read-only review finished. Existing families "
        "and source data were not replaced.",
        "migration_copy_cancelled": "Review discarded. Any already-created copy and "
        "saved retry intent were preserved.",
        "migration_copy_intent_invalid": "Saved retry coordinates do not match this "
        "review. They were not overwritten.",
        "article_invalid_url": "Use a public HTTPS page on the standard port, "
        "without login details or a fragment.",
        "chat_unavailable": "Conversation has changed or is unavailable. Refresh "
        "the card before sending again.",
        "chat_busy": "Several conversations are already in progress. Try again "
        "shortly; no new action was started.",
        "chat_context_expired": "This request's retry context has expired. Check "
        "the current result before sending a new command.",
        "chat_context_full": "The safe retry-context limit is reached. Existing "
        "commands are not repeated; try again later.",
        "article_timeout": "The page did not respond within the time limit. No "
        "family action was performed.",
        "article_unavailable": "The public page could not be retrieved.",
        "article_unsupported": "This page format or encoding is not supported. Use "
        "a plain-text or HTML article.",
        "article_too_large": "The page exceeds the article reading size limit.",
        "article_invalid_content": "The page did not contain readable text in a supported format.",
        "backup_in_progress": "A Home Assistant backup is being prepared. Try the "
        "same action after it finishes.",
        "migration_shadow_read_only": "This migration copy is read-only. Messages, "
        "devices and changes are disabled; activation "
        "requires a separate reviewed migration.",
        "migration_shadow_invalid": "This migration copy has unsafe or invalid "
        "isolation settings. It was not started.",
        "invalid_field": "Check the entered value.",
        "forbidden": "You do not have permission for this action.",
        "unknown_member": "Family member not found.",
        "not_found": "Record not found.",
        "conflict": "This record changed. Refresh and try again.",
        "idempotency_conflict": "This command ID was already used for a different action.",
        "invalid_transition": "This action is not available in the current state.",
        "duplicate_identity": "This Home Assistant account is already linked.",
        "last_owner": "Keep at least one active owner.",
        "unknown_action": "Unknown action.",
        "module_disabled": "This module is disabled.",
        "unsupported_schema": "The saved data requires a different integration version.",
        "not_ready": "The household is not loaded.",
        "unit_mismatch": "The purchase unit does not match the item.",
        "command_too_large": "The command is too large.",
        "photo_required": "A verified photo report is required.",
        "storage_error": "Could not save the change. It was not applied.",
        "admin_required": "A Home Assistant administrator must create the household.",
        "alarm_already_active": "This person already has an active wake-up check.",
        "schedule_overlap": "An enabled alarm already uses this time and these days.",
        "challenge_expired": "This wake-up check expired. Open the latest one.",
        "device_unavailable": "The siren is unavailable.",
        "device_unsupported": "The siren must support both on and off.",
        "device_confirmation_required": "Confirm the dedicated wake-up device before enabling it.",
        "device_already_assigned": "This siren is already assigned to another person or household.",
        "device_command_failed": "The siren did not accept the command.",
        "scheduler_failed": "The scheduler could not complete a state transition.",
        "telegram_invalid_token": "The bot token is invalid or revoked.",
        "telegram_polling_conflict": "This bot is already used by another poller. "
        "Stop that consumer before connecting it here.",
        "telegram_webhook_conflict": "This bot has an existing webhook. Remove it "
        "in its owning application before connecting.",
        "telegram_unreachable": "Could not connect to Telegram.",
        "telegram_timeout": "Telegram did not respond in time.",
        "telegram_rate_limited": "Telegram asked to wait. Try again shortly.",
        "telegram_chat_blocked": "The bot is blocked or cannot access this chat.",
        "telegram_api_error": "Telegram could not complete the request.",
        "telegram_bad_response": "Telegram returned an unexpected response.",
        "telegram_not_ready": "Connect and enable your Telegram bot first.",
        "telegram_enrollment_expired": "The enrollment code has expired or was "
        "already used. Generate a new code.",
        "telegram_waiting": "No enrollment message received yet. Send the command and try again.",
        "telegram_not_confirmed": "The detected chat was not confirmed. No access was granted.",
        "ambiguous_member": "Several people match this name. Use a unique name or member ID.",
        "retry_confirmation_required": "Confirm that resending may create a duplicate message.",
        "wrong_answer": "Not quite — try the current wake-up check again.",
        "context_required": "Reply to one specific task or include its ID.",
        "ambiguous_command": "The action or its target is ambiguous. Nothing was changed.",
        "invalid_deadline": "Specify a valid future deadline with an unambiguous time.",
        "invalid_alarm_days": "Specify the alarm days explicitly, for example "
        "weekdays, weekends or Monday and Wednesday. No "
        "schedule was changed.",
        "provider_invalid_url": "Use an explicit HTTP(S) provider base URL without "
        "credentials, query or fragment. HTTP requires "
        "consent.",
        "provider_authentication": "The provider rejected access. Check its API key "
        "or enabled JSON search format.",
        "provider_unreachable": "The configured provider could not be reached.",
        "provider_timeout": "The model did not respond in time. Ordinary commands still work.",
        "provider_bad_response": "The model or search provider returned an invalid "
        "response. Nothing was executed.",
        "provider_model_missing": "The selected model is not installed on this Ollama server.",
        "provider_not_configured": "Configure and enable a language provider in "
        "Family Assistant settings.",
        "provider_key_scope": "The server URL changed. Enter a new key or "
        "explicitly clear the old key.",
        "search_not_configured": "Internet search is not configured. Connect "
        "SearXNG with JSON output enabled.",
        "search_query_not_grounded": "I could not form a public search query "
        "without sending private context. Specify a "
        "public search phrase.",
        "proposal_expired": "This proposal expired or was already handled. Send the request again.",
        "assistant_busy": "Several requests are already queued. Ordinary commands still work.",
        "assistant_job_expired": "The queued request expired. Nothing was executed. "
        "Please send it again.",
        "learning_template_required": "Use an unrecognized phrase and a supported "
        "reusable command without a fixed record ID "
        "or date. Built-in commands cannot be "
        "replaced.",
        "learning_limit": "This account reached its 200-phrase limit. Update an existing phrase.",
        "network_url": "Use the router's HTTPS base URL without credentials, query or fragment.",
        "network_certificate": "The router certificate is not trusted or the CA "
        "certificate is invalid. Do not disable TLS "
        "verification.",
        "network_operation": "This RouterOS operation is not allowed.",
        "network_response": "RouterOS returned an invalid or oversized response. "
        "Previous data was retained.",
        "network_version": "RouterOS 7 is required for this REST connection.",
        "network_authentication": "RouterOS rejected authentication. Check "
        "credentials, allowed source address and rest-api "
        "permission; RouterOS 7.20.1 also requires api.",
        "network_permission": "The RouterOS account lacks permission for this table.",
        "network_missing": "This RouterOS table is not available on the device.",
        "network_rejected": "RouterOS rejected the request. Check parameters or device logs.",
        "network_unreachable": "The router could not be reached. Previous data was retained.",
        "network_timeout": "The router did not respond in time. Previous data was retained.",
        "network_not_configured": "Enable and configure the MikroTik connection first.",
        "network_credential_scope": "Enter the password again when changing the "
        "router URL or username.",
        "network_connected": "RouterOS inventory was read successfully.",
        "network_target": "The selected lease is missing, inactive or unsupported. "
        "Refresh the inventory.",
        "network_conflict": "The lease identity, IP or server is ambiguous or "
        "changed. No further change was applied.",
        "network_protected": "This target is protected or has no valid unicast MAC.",
        "network_subnet": "The IP, DHCP server and interface subnet could not be verified.",
        "network_readonly": "Router writes are disabled in connection settings.",
        "network_recovery_consent": "Confirm DHCP recovery: rollback of conversion "
        "removes the new reservation; dynamic leases "
        "return through DHCP renewal, not an exact "
        "restoration.",
        "network_confirmation": "Review the selected records and explicitly confirm this plan.",
        "network_readback": "The router read-back did not match the requested "
        "result. Check the plan; do not assume success.",
        "network_management_required": "Specify and confirm protected HA-host and "
        "administration-device MACs before allowing "
        "writes.",
        "network_stale": "The inventory is too old. Read the router again before preparing a plan.",
        "network_busy": "Another network plan is still running. Wait for its verified result.",
        "network_time_window": "Use increasing daily windows, such as 08:00-22:00. "
        "Split an overnight window between two days.",
        "network_clock": "Router clock or time zone differs from this household. "
        "Check its clock/NTP before changing schedules.",
        "network_kid_membership": "The entire profile membership must match the "
        "explicitly selected devices. Disabled, dynamic "
        "or changed members require review.",
        "network_kid_unmanaged": "The owner must explicitly adopt this child's "
        "RouterOS profile and devices first.",
        "network_timer_required": "A verified RouterOS 7.16+ expiry/startup timer "
        "is required. Temporary access was not safely "
        "enabled.",
        "insufficient_points": "Not enough available points. Existing requests reserve their cost.",
        "reward_expired": "This privilege request expired. Submit a new request.",
        "confirmation_required": "Confirm that shared confirmed events may be "
        "visible to other Home Assistant users.",
        "media_invalid": "The photo could not be verified. Use a static JPEG, PNG or WebP.",
        "media_too_large": "The photo exceeds the file or image-size limit.",
        "media_unavailable": "Could not confirm the photo operation. Retry the same "
        "reviewed action.",
        "capacity_reached": "The local inventory capacity is reached. Existing "
        "records and history are preserved; new changes are "
        "stopped.",
        "quota_exceeded": "The private photo quota is full. Unattached uploads "
        "expire automatically.",
    },
    "ru": {
        "migration_prepare_source_invalid": "Экспорты или дополнительные ID "
        "некорректны, не поддерживаются или "
        "слишком велики. Подготовьте "
        "исправленный согласованный экспорт; "
        "копия не записана.",
        "migration_prepare_selection_invalid": "Выберите допустимого участника, "
        "полный список проверяющих или файл "
        "в пределах лимита для этой "
        "страницы. Сопоставление не принято.",
        "migration_prepare_policy_changed": "Указанный полный список прежних "
        "проверяющих отличается от родителей "
        "новой семьи. Отмените проверку и "
        "согласуйте старые права и новые роли; "
        "не исключайте проверяющих ради обхода "
        "проверки.",
        "migration_copy_bundle_invalid": "Архив некорректен, неполон или слишком "
        "велик. Загрузите исправленный ZIP по "
        "инструкции; источник не менялся.",
        "migration_copy_source_unsettled": "В источнике не сходятся штрафы за "
        "задачи/будильники или не завершена "
        "отмена баллов. Копия не записана. "
        "Сначала согласуйте исходные записи, "
        "затем подготовьте и проверьте новый "
        "согласованный экспорт; не удаляйте "
        "историю ради обхода проверки.",
        "migration_copy_primary_owner_required": "Нужен первоначальный владелец "
        "семьи, который также является "
        "действующим администратором HA.",
        "migration_copy_confirmation_required": "Подтвердите именно показанную "
        "сейчас страницу или отпечаток.",
        "migration_copy_busy": "Другая проверка активна. Завершите её или дождитесь "
        "истечения её 15-минутного окна.",
        "migration_copy_review_changed": "Владелец, участники, модуль или срок "
        "проверки изменились. Проверьте заново; "
        "для повтора используйте тот же архив и "
        "название копии.",
        "migration_copy_conversion_required": "Нужно исправить записи, права "
        "проверяющих или исторические фото. "
        "Частичная копия не создана.",
        "migration_copy_retry_required": "Результат не подтверждён. Повторите это "
        "же проверенное действие. После "
        "перезапуска используйте тот же архив и "
        "название копии; не создавайте другую "
        "цель.",
        "migration_copy_not_loaded": "Защищённая копия зарегистрирована, но не "
        "загружена. Проверьте состояние интеграции; "
        "принудительного запуска не было.",
        "migration_copy_no_pending": "В журнале нет попыток этой семьи. Для старых "
        "попыток нужен исходный архив.",
        "migration_copy_partial_bundle_required": "Копия сохранена не полностью. "
        "Используйте исходный ZIP и "
        "название копии для проверенного "
        "восстановления.",
        "migration_copy_incompatible_bundle_required": "Данные, участники или "
        "настройки изменились. "
        "Продолжение заблокировано; "
        "перед повтором проверьте "
        "исходный архив и выбранную "
        "семью.",
        "migration_copy_index_invalid": "Не удалось проверить приватный журнал "
        "копий. Ничего не обнулено и не удалено.",
        "migration_copy_index_full": "В приватном журнале достигнут предел в 16 "
        "попыток. Старые попытки сохранены и не "
        "удаляются автоматически.",
        "migration_copy_finished": "Проверка копии завершена. Рабочие семьи и "
        "исходные данные не заменялись.",
        "migration_copy_cancelled": "Проверка отменена. Уже созданная копия и "
        "сохранённый план повтора не удалялись.",
        "migration_copy_intent_invalid": "Сохранённые параметры повтора не "
        "совпадают с проверкой. Они не "
        "перезаписывались.",
        "article_invalid_url": "Укажите публичную HTTPS-страницу со стандартным "
        "портом, без логина, пароля и фрагмента.",
        "chat_unavailable": "Разговорный модуль изменился или недоступен. Обновите "
        "карточку перед новой отправкой.",
        "chat_busy": "Несколько обращений уже обрабатываются. Попробуйте чуть "
        "позже; новое действие не запускалось.",
        "chat_context_expired": "Контекст повторной отправки этого запроса истёк. "
        "Проверьте текущий результат перед новой командой.",
        "chat_context_full": "Достигнут безопасный предел контекстов повторной "
        "отправки. Прежние команды не повторяются; попробуйте "
        "позднее.",
        "article_timeout": "Страница не ответила вовремя. Никаких семейных действий не выполнено.",
        "article_unavailable": "Не удалось загрузить публичную страницу.",
        "article_unsupported": "Формат или кодировка страницы не поддерживается. "
        "Нужна статья в HTML или обычном тексте.",
        "article_too_large": "Страница превышает ограничение размера для чтения статей.",
        "article_invalid_content": "На странице не найден читаемый текст в поддерживаемом формате.",
        "backup_in_progress": "Создаётся резервная копия Home Assistant. Повторите "
        "то же действие после её завершения.",
        "migration_shadow_read_only": "Это копия для проверки переноса, доступная "
        "только для чтения. Сообщения, устройства и "
        "изменения отключены; активация требует "
        "отдельной проверки миграции.",
        "migration_shadow_invalid": "У копии для переноса неверные или небезопасные "
        "настройки изоляции. Она не запущена.",
        "invalid_field": "Проверьте введённое значение.",
        "forbidden": "У вас нет права на это действие.",
        "unknown_member": "Участник семьи не найден.",
        "not_found": "Запись не найдена.",
        "conflict": "Запись уже изменилась. Обновите страницу.",
        "idempotency_conflict": "Этот ID команды уже использован для другого действия.",
        "invalid_transition": "Действие недоступно в текущем состоянии.",
        "duplicate_identity": "Этот пользователь Home Assistant уже привязан.",
        "last_owner": "Должен остаться хотя бы один активный владелец.",
        "unknown_action": "Неизвестное действие.",
        "module_disabled": "Модуль выключен.",
        "unsupported_schema": "Для сохранённых данных нужна другая версия интеграции.",
        "not_ready": "Семейное пространство не загружено.",
        "unit_mismatch": "Единицы покупки не совпадают с позицией.",
        "command_too_large": "Команда слишком большая.",
        "photo_required": "Нужен подтверждённый фотоотчёт.",
        "storage_error": "Не удалось сохранить изменение. Оно не применено.",
        "admin_required": "Создать семейное пространство может администратор Home Assistant.",
        "alarm_already_active": "У участника уже идёт проверка пробуждения.",
        "schedule_overlap": "На эти дни и время уже включён будильник.",
        "challenge_expired": "Проверка пробуждения устарела. Откройте новую.",
        "device_unavailable": "Сирена недоступна.",
        "device_unsupported": "Сирена должна поддерживать включение и выключение.",
        "device_confirmation_required": "Подтвердите использование отдельной сирены "
        "для пробуждения.",
        "device_already_assigned": "Сирена уже назначена другому участнику или семье.",
        "device_command_failed": "Сирена не приняла команду.",
        "scheduler_failed": "Планировщик не смог сохранить переход состояния.",
        "telegram_invalid_token": "Токен бота неверен или отозван.",
        "telegram_polling_conflict": "Бота уже опрашивает другая система. "
        "Остановите её перед подключением здесь.",
        "telegram_webhook_conflict": "У бота есть webhook. Отключите его в "
        "использующем его приложении перед "
        "подключением.",
        "telegram_unreachable": "Не удалось соединиться с Telegram.",
        "telegram_timeout": "Telegram не ответил вовремя.",
        "telegram_rate_limited": "Telegram просит подождать. Повторите чуть позже.",
        "telegram_chat_blocked": "Бот заблокирован или не имеет доступа к чату.",
        "telegram_api_error": "Telegram не смог выполнить запрос.",
        "telegram_bad_response": "Telegram вернул неожиданный ответ.",
        "telegram_not_ready": "Сначала подключите и включите своего Telegram-бота.",
        "telegram_enrollment_expired": "Код истёк или уже использован. Создайте новый.",
        "telegram_waiting": "Сообщение с кодом пока не получено. Отправьте команду и повторите.",
        "telegram_not_confirmed": "Найденный чат не подтверждён. Доступ не выдан.",
        "ambiguous_member": "Имя подходит нескольким участникам. Укажите уникальное имя или ID.",
        "retry_confirmation_required": "Подтвердите, что повторная отправка может "
        "создать дубликат.",
        "wrong_answer": "Не совсем — попробуйте решить текущую задачу ещё раз.",
        "context_required": "Ответьте на сообщение об одной конкретной задаче или укажите её ID.",
        "ambiguous_command": "Действие или его объект неоднозначны. Ничего не изменено.",
        "invalid_deadline": "Укажите корректный будущий срок с однозначным временем.",
        "invalid_alarm_days": "Укажите дни будильника явно: например, по будням, по "
        "выходным или в понедельник и среду. Расписание не "
        "изменено.",
        "provider_invalid_url": "Укажите базовый HTTP(S) URL сервера без логина, "
        "пароля, параметров и фрагмента. Для HTTP нужно "
        "согласие.",
        "provider_authentication": "Сервер отказал в доступе. Проверьте ключ API "
        "или разрешение JSON-формата поиска.",
        "provider_unreachable": "Настроенный сервер недоступен.",
        "provider_timeout": "Модель не ответила вовремя. Обычные команды продолжают работать.",
        "provider_bad_response": "Модель или поиск вернули неверный формат. Никакие "
        "действия не выполнены.",
        "provider_model_missing": "Выбранная модель не установлена на этом сервере Ollama.",
        "provider_not_configured": "Настройте и включите языковую модель в "
        "параметрах Family Assistant.",
        "provider_key_scope": "Адрес сервера изменился. Введите новый ключ либо "
        "явно очистите старый.",
        "search_not_configured": "Интернет-поиск не настроен. Подключите SearXNG с "
        "включённым JSON-форматом.",
        "search_query_not_grounded": "Не удалось составить открытый поисковый "
        "запрос без личного контекста. Укажите "
        "поисковую фразу.",
        "proposal_expired": "Предложение истекло или уже обработано. Отправьте запрос заново.",
        "assistant_busy": "Несколько обращений уже в очереди. Обычные команды работают.",
        "assistant_job_expired": "Время ожидания обращения истекло. Ничего не "
        "выполнено. Отправьте запрос заново.",
        "learning_template_required": "Укажите непонятную фразу и понятную "
        "повторяемую команду без конкретного ID или "
        "даты. Встроенные команды нельзя заменять.",
        "learning_limit": "Для аккаунта достигнут предел 200 фраз. Измените существующую фразу.",
        "network_url": "Укажите HTTPS-адрес роутера без пароля, параметров и фрагмента.",
        "network_certificate": "Сертификат роутера не доверенный или CA-сертификат "
        "неверен. Не отключайте проверку TLS.",
        "network_operation": "Эта операция RouterOS не разрешена.",
        "network_response": "RouterOS вернул неверный или слишком большой ответ. "
        "Предыдущие данные сохранены.",
        "network_version": "Для REST-подключения требуется RouterOS 7.",
        "network_authentication": "RouterOS отклонил вход. Проверьте пароль, "
        "допустимый адрес и право rest-api; RouterOS "
        "7.20.1 также требует api.",
        "network_permission": "У аккаунта RouterOS нет права чтения этой таблицы.",
        "network_missing": "Эта таблица RouterOS недоступна на устройстве.",
        "network_rejected": "RouterOS отклонил запрос. Проверьте параметры или журнал устройства.",
        "network_unreachable": "Роутер недоступен. Предыдущие данные сохранены.",
        "network_timeout": "Роутер не ответил вовремя. Предыдущие данные сохранены.",
        "network_not_configured": "Сначала настройте и включите подключение к MikroTik.",
        "network_credential_scope": "При смене адреса роутера или пользователя "
        "введите пароль заново.",
        "network_connected": "Инвентарь RouterOS успешно прочитан.",
        "network_target": "Выбранный лиз отсутствует, неактивен или не "
        "поддерживается. Обновите инвентарь.",
        "network_conflict": "MAC, IP или сервер лиза неоднозначны либо изменились. "
        "Дальнейшее изменение не применено.",
        "network_protected": "Это устройство защищено или у него нет корректного "
        "индивидуального MAC.",
        "network_subnet": "Не удалось проверить соответствие IP, DHCP-сервера и "
        "подсети интерфейса.",
        "network_readonly": "Запись на роутер выключена в настройках подключения.",
        "network_recovery_consent": "Подтвердите восстановление DHCP: откат "
        "преобразования удаляет новую резервацию; "
        "динамический лиз появится при DHCP-обновлении, "
        "это не точное восстановление.",
        "network_confirmation": "Просмотрите выбранные записи и явно подтвердите план.",
        "network_readback": "Повторное чтение роутера не подтвердило ожидаемый "
        "результат. Проверьте план; успех не подтверждён.",
        "network_management_required": "Перед разрешением записи задайте и "
        "подтвердите защищённые MAC хоста HA и "
        "устройства администратора.",
        "network_stale": "Инвентарь устарел. Перечитайте роутер перед подготовкой плана.",
        "network_busy": "Другой сетевой план ещё выполняется. Дождитесь проверенного результата.",
        "network_time_window": "Интервалы суток должны идти вперёд, например "
        "08:00-22:00. Ночной интервал разделите между двумя "
        "днями.",
        "network_clock": "Часы или часовой пояс роутера не совпадают с семьёй. "
        "Проверьте часы/NTP перед изменением расписания.",
        "network_kid_membership": "Полный состав профиля должен совпадать с "
        "выбранными устройствами. Отключённые, "
        "динамические и изменённые записи требуют "
        "проверки.",
        "network_kid_unmanaged": "Сначала владелец должен явно передать профиль "
        "ребёнка и его устройства RouterOS под управление.",
        "network_timer_required": "Нужен проверенный таймер окончания и запуска в "
        "RouterOS 7.16+. Временный доступ не удалось "
        "безопасно включить.",
        "insufficient_points": "Недостаточно доступных баллов: действующие заявки "
        "резервируют свою стоимость.",
        "reward_expired": "Срок заявки на привилегию истёк. Создайте новую заявку.",
        "confirmation_required": "Подтвердите, что общие одобренные события могут "
        "быть видны другим пользователям Home Assistant.",
        "media_invalid": "Не удалось проверить фото. Выберите обычное изображение "
        "JPEG, PNG или WebP.",
        "media_too_large": "Фото превышает ограничение размера файла или изображения.",
        "media_unavailable": "Не удалось подтвердить операцию с фото. Повторите то "
        "же проверенное действие.",
        "capacity_reached": "Достигнут лимит локального журнала. Записи и история "
        "сохранены; новые изменения не добавляются.",
        "quota_exceeded": "Квота фото заполнена. Неприкреплённые загрузки удаляются "
        "после истечения срока.",
    },
    "uk": {
        "migration_prepare_source_invalid": "Експорти чи додаткові ID некоректні, "
        "не підтримуються або завеликі. "
        "Підготуйте виправлений узгоджений "
        "експорт; копію не записано.",
        "migration_prepare_selection_invalid": "Виберіть дозволеного учасника, "
        "повний перелік перевіряльників чи "
        "файл у межах ліміту для цієї "
        "сторінки. Зіставлення не прийнято.",
        "migration_prepare_policy_changed": "Зазначений повний перелік старих "
        "перевіряльників відрізняється від "
        "батьків нової родини. Скасуйте "
        "перевірку та узгодьте старі права й "
        "нові ролі; не вилучайте "
        "перевіряльників заради обходу "
        "перевірки.",
        "migration_copy_bundle_invalid": "Архів некоректний, неповний або "
        "завеликий. Завантажте виправлений ZIP за "
        "інструкцією; джерело не змінювалося.",
        "migration_copy_source_unsettled": "У джерелі не збігаються штрафи за "
        "завдання/будильники або не завершено "
        "скасування балів. Копію не записано. "
        "Спочатку узгодьте вихідні записи, потім "
        "підготуйте й перевірте новий узгоджений "
        "експорт; не видаляйте історію заради "
        "обходу перевірки.",
        "migration_copy_primary_owner_required": "Потрібен початковий власник "
        "родини, який також є активним "
        "адміністратором HA.",
        "migration_copy_confirmation_required": "Підтвердьте саме показану зараз "
        "сторінку або відбиток.",
        "migration_copy_busy": "Інша перевірка активна. Завершіть її або "
        "дочекайтеся завершення її 15-хвилинного вікна.",
        "migration_copy_review_changed": "Власник, учасники, модуль чи строк "
        "перевірки змінилися. Перевірте знову; для "
        "повтору використовуйте той самий архів і "
        "назву копії.",
        "migration_copy_conversion_required": "Потрібно виправити записи, права "
        "перевіряльників чи історичні фото. "
        "Часткової копії не створено.",
        "migration_copy_retry_required": "Результат не підтверджений. Повторіть цю "
        "саму перевірену дію. Після перезапуску "
        "використовуйте той самий архів і назву "
        "копії; не створюйте іншу ціль.",
        "migration_copy_not_loaded": "Захищену копію зареєстровано, але не "
        "завантажено. Перевірте стан інтеграції; "
        "примусового запуску не було.",
        "migration_copy_no_pending": "У журналі немає спроб цієї сім’ї. Для старих "
        "спроб потрібен вихідний архів.",
        "migration_copy_partial_bundle_required": "Копія збережена не повністю. "
        "Використайте вихідний ZIP і "
        "назву копії для перевіреного "
        "відновлення.",
        "migration_copy_incompatible_bundle_required": "Дані, учасники або "
        "налаштування змінилися. "
        "Продовження заблоковано; "
        "перед повтором перевірте "
        "вихідний архів і вибрану "
        "сім’ю.",
        "migration_copy_index_invalid": "Не вдалося перевірити приватний журнал "
        "копій. Нічого не обнулено й не видалено.",
        "migration_copy_index_full": "У приватному журналі досягнуто межі в 16 "
        "спроб. Попередні спроби збережено й не "
        "видаляються автоматично.",
        "migration_copy_finished": "Перевірку копії завершено. Робочі родини й "
        "вихідні дані не замінювали.",
        "migration_copy_cancelled": "Перевірку скасовано. Уже створену копію та "
        "збережений план повтору не видаляли.",
        "migration_copy_intent_invalid": "Збережені параметри повтору не збігаються "
        "з перевіркою. Їх не перезаписували.",
        "article_invalid_url": "Укажіть публічну HTTPS-сторінку зі стандартним "
        "портом, без логіна, пароля та фрагмента.",
        "chat_unavailable": "Розмовний модуль змінився або недоступний. Оновіть "
        "картку перед новим надсиланням.",
        "chat_busy": "Кілька звернень уже обробляються. Спробуйте трохи пізніше; "
        "нову дію не запущено.",
        "chat_context_expired": "Контекст повторного надсилання цього запиту сплив. "
        "Перевірте поточний результат перед новою командою.",
        "chat_context_full": "Досягнуто безпечної межі контекстів повторного "
        "надсилання. Попередні команди не повторюються; "
        "спробуйте пізніше.",
        "article_timeout": "Сторінка не відповіла вчасно. Жодних сімейних дій не виконано.",
        "article_unavailable": "Не вдалося завантажити публічну сторінку.",
        "article_unsupported": "Формат або кодування сторінки не підтримується. "
        "Потрібна стаття в HTML або звичайному тексті.",
        "article_too_large": "Сторінка перевищує обмеження розміру для читання статей.",
        "article_invalid_content": "На сторінці не знайдено читабельного тексту в "
        "підтримуваному форматі.",
        "backup_in_progress": "Створюється резервна копія Home Assistant. Повторіть "
        "ту саму дію після її завершення.",
        "migration_shadow_read_only": "Це копія для перевірки перенесення, доступна "
        "лише для читання. Повідомлення, пристрої та "
        "зміни вимкнено; активація потребує окремої "
        "перевірки міграції.",
        "migration_shadow_invalid": "Копія для перенесення має неправильні або "
        "небезпечні налаштування ізоляції. Її не "
        "запущено.",
        "invalid_field": "Перевірте введене значення.",
        "forbidden": "Ви не маєте права на цю дію.",
        "unknown_member": "Учасника родини не знайдено.",
        "not_found": "Запис не знайдено.",
        "conflict": "Запис уже змінився. Оновіть сторінку.",
        "idempotency_conflict": "Цей ID команди вже використано для іншої дії.",
        "invalid_transition": "Дія недоступна в поточному стані.",
        "duplicate_identity": "Цей користувач Home Assistant уже прив’язаний.",
        "last_owner": "Має залишитися хоча б один активний власник.",
        "unknown_action": "Невідома дія.",
        "module_disabled": "Модуль вимкнено.",
        "unsupported_schema": "Для збережених даних потрібна інша версія інтеграції.",
        "not_ready": "Родинний простір не завантажено.",
        "unit_mismatch": "Одиниці покупки не збігаються з позицією.",
        "command_too_large": "Команда завелика.",
        "photo_required": "Потрібен підтверджений фотозвіт.",
        "storage_error": "Не вдалося зберегти зміну. Її не застосовано.",
        "admin_required": "Створити родинний простір може адміністратор Home Assistant.",
        "alarm_already_active": "В учасника вже триває перевірка пробудження.",
        "schedule_overlap": "На ці дні та час уже ввімкнено будильник.",
        "challenge_expired": "Перевірка пробудження застаріла. Відкрийте нову.",
        "device_unavailable": "Сирена недоступна.",
        "device_unsupported": "Сирена має підтримувати ввімкнення та вимкнення.",
        "device_confirmation_required": "Підтвердьте використання окремої сирени для пробудження.",
        "device_already_assigned": "Сирену вже призначено іншому учаснику або родині.",
        "device_command_failed": "Сирена не прийняла команду.",
        "scheduler_failed": "Планувальник не зміг зберегти перехід стану.",
        "telegram_invalid_token": "Токен бота неправильний або відкликаний.",
        "telegram_polling_conflict": "Бота вже опитує інша система. Зупиніть її "
        "перед підключенням тут.",
        "telegram_webhook_conflict": "Бот має webhook. Вимкніть його в застосунку, "
        "що ним користується, перед підключенням.",
        "telegram_unreachable": "Не вдалося з’єднатися з Telegram.",
        "telegram_timeout": "Telegram не відповів вчасно.",
        "telegram_rate_limited": "Telegram просить зачекати. Повторіть трохи пізніше.",
        "telegram_chat_blocked": "Бота заблоковано або він не має доступу до чату.",
        "telegram_api_error": "Telegram не зміг виконати запит.",
        "telegram_bad_response": "Telegram повернув неочікувану відповідь.",
        "telegram_not_ready": "Спочатку підключіть та ввімкніть власного Telegram-бота.",
        "telegram_enrollment_expired": "Код застарів або вже використаний. Створіть новий.",
        "telegram_waiting": "Повідомлення з кодом ще не отримано. Надішліть команду й повторіть.",
        "telegram_not_confirmed": "Знайдений чат не підтверджено. Доступ не надано.",
        "ambiguous_member": "Ім’я відповідає кільком учасникам. Укажіть унікальне ім’я або ID.",
        "retry_confirmation_required": "Підтвердьте, що повторне надсилання може "
        "створити дублікат.",
        "wrong_answer": "Не зовсім — спробуйте розв’язати поточну задачу ще раз.",
        "context_required": "Дайте відповідь на повідомлення про одне конкретне "
        "завдання або вкажіть його ID.",
        "ambiguous_command": "Дія або її об’єкт неоднозначні. Нічого не змінено.",
        "invalid_deadline": "Вкажіть коректний майбутній термін з однозначним часом.",
        "invalid_alarm_days": "Укажіть дні будильника явно: наприклад, у будні, у "
        "вихідні або в понеділок і середу. Розклад не "
        "змінено.",
        "provider_invalid_url": "Укажіть базовий HTTP(S) URL сервера без логіна, "
        "пароля, параметрів і фрагмента. Для HTTP потрібна "
        "згода.",
        "provider_authentication": "Сервер відмовив у доступі. Перевірте ключ API "
        "або дозвіл JSON-формату пошуку.",
        "provider_unreachable": "Налаштований сервер недоступний.",
        "provider_timeout": "Модель не відповіла вчасно. Звичайні команди працюють далі.",
        "provider_bad_response": "Модель або пошук повернули неправильний формат. "
        "Жодних дій не виконано.",
        "provider_model_missing": "Вибрана модель не встановлена на цьому сервері Ollama.",
        "provider_not_configured": "Налаштуйте й увімкніть мовну модель у "
        "параметрах Family Assistant.",
        "provider_key_scope": "Адреса сервера змінилася. Введіть новий ключ або "
        "явно очистьте старий.",
        "search_not_configured": "Інтернет-пошук не налаштовано. Підключіть SearXNG "
        "з увімкненим JSON-форматом.",
        "search_query_not_grounded": "Не вдалося скласти відкритий пошуковий запит "
        "без особистого контексту. Укажіть пошукову "
        "фразу.",
        "proposal_expired": "Пропозиція прострочена або вже опрацьована. Надішліть запит знову.",
        "assistant_busy": "Кілька звернень уже в черзі. Звичайні команди працюють.",
        "assistant_job_expired": "Час очікування звернення минув. Нічого не "
        "виконано. Надішліть запит знову.",
        "learning_template_required": "Укажіть незрозумілу фразу та підтримувану "
        "повторювану команду без конкретного ID чи "
        "дати. Вбудовані команди не можна замінювати.",
        "learning_limit": "Для акаунта досягнуто межу 200 фраз. Змініть наявну фразу.",
        "network_url": "Укажіть HTTPS-адресу роутера без пароля, параметрів і фрагмента.",
        "network_certificate": "Сертифікат роутера не є довіреним або CA-сертифікат "
        "хибний. Не вимикайте перевірку TLS.",
        "network_operation": "Цю операцію RouterOS не дозволено.",
        "network_response": "RouterOS повернув хибну або завелику відповідь. "
        "Попередні дані збережено.",
        "network_version": "Для REST-підключення потрібна RouterOS 7.",
        "network_authentication": "RouterOS відхилив вхід. Перевірте пароль, "
        "дозволену адресу та право rest-api; RouterOS "
        "7.20.1 також потребує api.",
        "network_permission": "Акаунт RouterOS не має права читання цієї таблиці.",
        "network_missing": "Ця таблиця RouterOS недоступна на пристрої.",
        "network_rejected": "RouterOS відхилив запит. Перевірте параметри або журнал пристрою.",
        "network_unreachable": "Роутер недоступний. Попередні дані збережено.",
        "network_timeout": "Роутер не відповів вчасно. Попередні дані збережено.",
        "network_not_configured": "Спочатку налаштуйте й увімкніть підключення до MikroTik.",
        "network_credential_scope": "При зміні адреси роутера чи користувача введіть пароль знову.",
        "network_connected": "Інвентар RouterOS успішно прочитано.",
        "network_target": "Вибраний ліз відсутній, неактивний або не підтримується. "
        "Оновіть інвентар.",
        "network_conflict": "MAC, IP або сервер ліза неоднозначні чи змінилися. "
        "Подальшу зміну не застосовано.",
        "network_protected": "Цей пристрій захищений або не має коректного індивідуального MAC.",
        "network_subnet": "Не вдалося перевірити відповідність IP, DHCP-сервера й "
        "підмережі інтерфейсу.",
        "network_readonly": "Запис на роутер вимкнено в параметрах підключення.",
        "network_recovery_consent": "Підтвердьте відновлення DHCP: відкат "
        "перетворення видаляє нову резервацію; "
        "динамічний ліз повернеться під час "
        "DHCP-оновлення, це не точне відновлення.",
        "network_confirmation": "Перегляньте вибрані записи й явно підтвердьте план.",
        "network_readback": "Повторне читання роутера не підтвердило очікуваний "
        "результат. Перевірте план; успіх не підтверджено.",
        "network_management_required": "Перед дозволом запису задайте й підтвердьте "
        "захищені MAC хоста HA та пристрою "
        "адміністратора.",
        "network_stale": "Інвентар застарів. Перечитайте роутер перед підготовкою плану.",
        "network_busy": "Інший мережевий план ще виконується. Дочекайтеся перевіреного результату.",
        "network_time_window": "Інтервали доби мають іти вперед, наприклад "
        "08:00-22:00. Нічний інтервал розділіть між двома "
        "днями.",
        "network_clock": "Годинник або часовий пояс роутера відрізняється від "
        "сімейного. Перевірте час/NTP до зміни розкладу.",
        "network_kid_membership": "Повний склад профілю має відповідати вибраним "
        "пристроям. Вимкнені, динамічні та змінені записи "
        "потребують перевірки.",
        "network_kid_unmanaged": "Спочатку власник має явно передати профіль дитини "
        "та її пристрої RouterOS під керування.",
        "network_timer_required": "Потрібен перевірений таймер завершення та "
        "запуску в RouterOS 7.16+. Тимчасовий доступ не "
        "вдалося безпечно увімкнути.",
        "insufficient_points": "Недостатньо доступних балів: чинні заявки "
        "резервують свою вартість.",
        "reward_expired": "Термін заявки на привілей минув. Створіть нову заявку.",
        "confirmation_required": "Підтвердьте, що спільні схвалені події можуть "
        "бути видимі іншим користувачам Home Assistant.",
        "media_invalid": "Не вдалося перевірити фото. Оберіть звичайне зображення "
        "JPEG, PNG або WebP.",
        "media_too_large": "Фото перевищує обмеження розміру файлу або зображення.",
        "media_unavailable": "Не вдалося підтвердити операцію з фото. Повторіть ту "
        "саму перевірену дію.",
        "capacity_reached": "Досягнуто ліміту локального журналу. Записи та історію "
        "збережено; нові зміни не додаються.",
        "quota_exceeded": "Квота фото заповнена. Неприкріплені завантаження "
        "видаляються після закінчення строку.",
    },
}
