"""Generated by tools/sync_locales.py; edit HA translation JSON instead."""

ERRORS = {
    "en": {
        "invalid_field": "Check the entered value.",
        "forbidden": "You do not have permission for this action.",
        "unknown_member": "Family member not found.",
        "not_found": "Record not found.",
        "conflict": "This record changed. Refresh and try again.",
        "idempotency_conflict": "This command ID was already used for a different action.",
        "invalid_transition": "This action is not available in the current state.",
        "duplicate_identity": "This Home Assistant account is already linked.",
        "last_owner": "Keep at least one active owner.",
        "unknown_action": "Unknown action.",
        "module_disabled": "This module is disabled.",
        "unsupported_schema": "The saved data requires a different integration version.",
        "not_ready": "The household is not loaded.",
        "unit_mismatch": "The purchase unit does not match the item.",
        "command_too_large": "The command is too large.",
        "photo_required": "A verified photo report is required.",
        "storage_error": "Could not save the change. It was not applied.",
        "admin_required": "A Home Assistant administrator must create the household.",
        "alarm_already_active": "This person already has an active wake-up check.",
        "schedule_overlap": "An enabled alarm already uses this time and these days.",
        "challenge_expired": "This wake-up check expired. Open the latest one.",
        "device_unavailable": "The siren is unavailable.",
        "device_unsupported": "The siren must support both on and off.",
        "device_confirmation_required": "Confirm the dedicated wake-up device before enabling it.",
        "device_already_assigned": "This siren is already assigned to another person or household.",
        "device_command_failed": "The siren did not accept the command.",
        "scheduler_failed": "The scheduler could not complete a state transition.",
        "telegram_invalid_token": "The bot token is invalid or revoked.",
        "telegram_polling_conflict": "This bot is already used by another poller. "
        "Stop that consumer before connecting it here.",
        "telegram_webhook_conflict": "This bot has an existing webhook. Remove it "
        "in its owning application before connecting.",
        "telegram_unreachable": "Could not connect to Telegram.",
        "telegram_timeout": "Telegram did not respond in time.",
        "telegram_rate_limited": "Telegram asked to wait. Try again shortly.",
        "telegram_chat_blocked": "The bot is blocked or cannot access this chat.",
        "telegram_api_error": "Telegram could not complete the request.",
        "telegram_bad_response": "Telegram returned an unexpected response.",
        "telegram_not_ready": "Connect and enable your Telegram bot first.",
        "telegram_enrollment_expired": "The enrollment code has expired or was "
        "already used. Generate a new code.",
        "telegram_waiting": "No enrollment message received yet. Send the command and try again.",
        "telegram_not_confirmed": "The detected chat was not confirmed. No access was granted.",
        "ambiguous_member": "Several people match this name. Use a unique name or member ID.",
        "retry_confirmation_required": "Confirm that resending may create a duplicate message.",
        "wrong_answer": "Not quite — try the current wake-up check again.",
        "context_required": "Reply to one specific task or include its ID.",
        "ambiguous_command": "The action or its target is ambiguous. Nothing was changed.",
        "invalid_deadline": "Specify a valid future deadline with an unambiguous time.",
        "provider_invalid_url": "Use an explicit HTTP(S) provider base URL without "
        "credentials, query or fragment. HTTP requires "
        "consent.",
        "provider_authentication": "The provider rejected access. Check its API key "
        "or enabled JSON search format.",
        "provider_unreachable": "The configured provider could not be reached.",
        "provider_timeout": "The model did not respond in time. Ordinary commands still work.",
        "provider_bad_response": "The model or search provider returned an invalid "
        "response. Nothing was executed.",
        "provider_model_missing": "The selected model is not installed on this Ollama server.",
        "provider_not_configured": "Configure and enable a language provider in "
        "Family Assistant settings.",
        "provider_key_scope": "The server URL changed. Enter a new key or "
        "explicitly clear the old key.",
        "search_not_configured": "Internet search is not configured. Connect "
        "SearXNG with JSON output enabled.",
        "search_query_not_grounded": "I could not form a public search query "
        "without sending private context. Specify a "
        "public search phrase.",
        "proposal_expired": "This proposal expired or was already handled. Send the request again.",
        "assistant_busy": "Several requests are already queued. Ordinary commands still work.",
        "assistant_job_expired": "The queued request expired. Nothing was executed. "
        "Please send it again.",
    },
    "ru": {
        "invalid_field": "Проверьте введённое значение.",
        "forbidden": "У вас нет права на это действие.",
        "unknown_member": "Участник семьи не найден.",
        "not_found": "Запись не найдена.",
        "conflict": "Запись уже изменилась. Обновите страницу.",
        "idempotency_conflict": "Этот ID команды уже использован для другого действия.",
        "invalid_transition": "Действие недоступно в текущем состоянии.",
        "duplicate_identity": "Этот пользователь Home Assistant уже привязан.",
        "last_owner": "Должен остаться хотя бы один активный владелец.",
        "unknown_action": "Неизвестное действие.",
        "module_disabled": "Модуль выключен.",
        "unsupported_schema": "Для сохранённых данных нужна другая версия интеграции.",
        "not_ready": "Семейное пространство не загружено.",
        "unit_mismatch": "Единицы покупки не совпадают с позицией.",
        "command_too_large": "Команда слишком большая.",
        "photo_required": "Нужен подтверждённый фотоотчёт.",
        "storage_error": "Не удалось сохранить изменение. Оно не применено.",
        "admin_required": "Создать семейное пространство может администратор Home Assistant.",
        "alarm_already_active": "У участника уже идёт проверка пробуждения.",
        "schedule_overlap": "На эти дни и время уже включён будильник.",
        "challenge_expired": "Проверка пробуждения устарела. Откройте новую.",
        "device_unavailable": "Сирена недоступна.",
        "device_unsupported": "Сирена должна поддерживать включение и выключение.",
        "device_confirmation_required": "Подтвердите использование отдельной сирены "
        "для пробуждения.",
        "device_already_assigned": "Сирена уже назначена другому участнику или семье.",
        "device_command_failed": "Сирена не приняла команду.",
        "scheduler_failed": "Планировщик не смог сохранить переход состояния.",
        "telegram_invalid_token": "Токен бота неверен или отозван.",
        "telegram_polling_conflict": "Бота уже опрашивает другая система. "
        "Остановите её перед подключением здесь.",
        "telegram_webhook_conflict": "У бота есть webhook. Отключите его в "
        "использующем его приложении перед "
        "подключением.",
        "telegram_unreachable": "Не удалось соединиться с Telegram.",
        "telegram_timeout": "Telegram не ответил вовремя.",
        "telegram_rate_limited": "Telegram просит подождать. Повторите чуть позже.",
        "telegram_chat_blocked": "Бот заблокирован или не имеет доступа к чату.",
        "telegram_api_error": "Telegram не смог выполнить запрос.",
        "telegram_bad_response": "Telegram вернул неожиданный ответ.",
        "telegram_not_ready": "Сначала подключите и включите своего Telegram-бота.",
        "telegram_enrollment_expired": "Код истёк или уже использован. Создайте новый.",
        "telegram_waiting": "Сообщение с кодом пока не получено. Отправьте команду и повторите.",
        "telegram_not_confirmed": "Найденный чат не подтверждён. Доступ не выдан.",
        "ambiguous_member": "Имя подходит нескольким участникам. Укажите уникальное имя или ID.",
        "retry_confirmation_required": "Подтвердите, что повторная отправка может "
        "создать дубликат.",
        "wrong_answer": "Не совсем — попробуйте решить текущую задачу ещё раз.",
        "context_required": "Ответьте на сообщение об одной конкретной задаче или укажите её ID.",
        "ambiguous_command": "Действие или его объект неоднозначны. Ничего не изменено.",
        "invalid_deadline": "Укажите корректный будущий срок с однозначным временем.",
        "provider_invalid_url": "Укажите базовый HTTP(S) URL сервера без логина, "
        "пароля, параметров и фрагмента. Для HTTP нужно "
        "согласие.",
        "provider_authentication": "Сервер отказал в доступе. Проверьте ключ API "
        "или разрешение JSON-формата поиска.",
        "provider_unreachable": "Настроенный сервер недоступен.",
        "provider_timeout": "Модель не ответила вовремя. Обычные команды продолжают работать.",
        "provider_bad_response": "Модель или поиск вернули неверный формат. Никакие "
        "действия не выполнены.",
        "provider_model_missing": "Выбранная модель не установлена на этом сервере Ollama.",
        "provider_not_configured": "Настройте и включите языковую модель в "
        "параметрах Family Assistant.",
        "provider_key_scope": "Адрес сервера изменился. Введите новый ключ либо "
        "явно очистите старый.",
        "search_not_configured": "Интернет-поиск не настроен. Подключите SearXNG с "
        "включённым JSON-форматом.",
        "search_query_not_grounded": "Не удалось составить открытый поисковый "
        "запрос без личного контекста. Укажите "
        "поисковую фразу.",
        "proposal_expired": "Предложение истекло или уже обработано. Отправьте запрос заново.",
        "assistant_busy": "Несколько обращений уже в очереди. Обычные команды работают.",
        "assistant_job_expired": "Время ожидания обращения истекло. Ничего не "
        "выполнено. Отправьте запрос заново.",
    },
    "uk": {
        "invalid_field": "Перевірте введене значення.",
        "forbidden": "Ви не маєте права на цю дію.",
        "unknown_member": "Учасника родини не знайдено.",
        "not_found": "Запис не знайдено.",
        "conflict": "Запис уже змінився. Оновіть сторінку.",
        "idempotency_conflict": "Цей ID команди вже використано для іншої дії.",
        "invalid_transition": "Дія недоступна в поточному стані.",
        "duplicate_identity": "Цей користувач Home Assistant уже прив’язаний.",
        "last_owner": "Має залишитися хоча б один активний власник.",
        "unknown_action": "Невідома дія.",
        "module_disabled": "Модуль вимкнено.",
        "unsupported_schema": "Для збережених даних потрібна інша версія інтеграції.",
        "not_ready": "Родинний простір не завантажено.",
        "unit_mismatch": "Одиниці покупки не збігаються з позицією.",
        "command_too_large": "Команда завелика.",
        "photo_required": "Потрібен підтверджений фотозвіт.",
        "storage_error": "Не вдалося зберегти зміну. Її не застосовано.",
        "admin_required": "Створити родинний простір може адміністратор Home Assistant.",
        "alarm_already_active": "В учасника вже триває перевірка пробудження.",
        "schedule_overlap": "На ці дні та час уже ввімкнено будильник.",
        "challenge_expired": "Перевірка пробудження застаріла. Відкрийте нову.",
        "device_unavailable": "Сирена недоступна.",
        "device_unsupported": "Сирена має підтримувати ввімкнення та вимкнення.",
        "device_confirmation_required": "Підтвердьте використання окремої сирени для пробудження.",
        "device_already_assigned": "Сирену вже призначено іншому учаснику або родині.",
        "device_command_failed": "Сирена не прийняла команду.",
        "scheduler_failed": "Планувальник не зміг зберегти перехід стану.",
        "telegram_invalid_token": "Токен бота неправильний або відкликаний.",
        "telegram_polling_conflict": "Бота вже опитує інша система. Зупиніть її "
        "перед підключенням тут.",
        "telegram_webhook_conflict": "Бот має webhook. Вимкніть його в застосунку, "
        "що ним користується, перед підключенням.",
        "telegram_unreachable": "Не вдалося з’єднатися з Telegram.",
        "telegram_timeout": "Telegram не відповів вчасно.",
        "telegram_rate_limited": "Telegram просить зачекати. Повторіть трохи пізніше.",
        "telegram_chat_blocked": "Бота заблоковано або він не має доступу до чату.",
        "telegram_api_error": "Telegram не зміг виконати запит.",
        "telegram_bad_response": "Telegram повернув неочікувану відповідь.",
        "telegram_not_ready": "Спочатку підключіть та ввімкніть власного Telegram-бота.",
        "telegram_enrollment_expired": "Код застарів або вже використаний. Створіть новий.",
        "telegram_waiting": "Повідомлення з кодом ще не отримано. Надішліть команду й повторіть.",
        "telegram_not_confirmed": "Знайдений чат не підтверджено. Доступ не надано.",
        "ambiguous_member": "Ім’я відповідає кільком учасникам. Укажіть унікальне ім’я або ID.",
        "retry_confirmation_required": "Підтвердьте, що повторне надсилання може "
        "створити дублікат.",
        "wrong_answer": "Не зовсім — спробуйте розв’язати поточну задачу ще раз.",
        "context_required": "Дайте відповідь на повідомлення про одне конкретне "
        "завдання або вкажіть його ID.",
        "ambiguous_command": "Дія або її об’єкт неоднозначні. Нічого не змінено.",
        "invalid_deadline": "Вкажіть коректний майбутній термін з однозначним часом.",
        "provider_invalid_url": "Укажіть базовий HTTP(S) URL сервера без логіна, "
        "пароля, параметрів і фрагмента. Для HTTP потрібна "
        "згода.",
        "provider_authentication": "Сервер відмовив у доступі. Перевірте ключ API "
        "або дозвіл JSON-формату пошуку.",
        "provider_unreachable": "Налаштований сервер недоступний.",
        "provider_timeout": "Модель не відповіла вчасно. Звичайні команди працюють далі.",
        "provider_bad_response": "Модель або пошук повернули неправильний формат. "
        "Жодних дій не виконано.",
        "provider_model_missing": "Вибрана модель не встановлена на цьому сервері Ollama.",
        "provider_not_configured": "Налаштуйте й увімкніть мовну модель у "
        "параметрах Family Assistant.",
        "provider_key_scope": "Адреса сервера змінилася. Введіть новий ключ або "
        "явно очистьте старий.",
        "search_not_configured": "Інтернет-пошук не налаштовано. Підключіть SearXNG "
        "з увімкненим JSON-форматом.",
        "search_query_not_grounded": "Не вдалося скласти відкритий пошуковий запит "
        "без особистого контексту. Укажіть пошукову "
        "фразу.",
        "proposal_expired": "Пропозиція прострочена або вже опрацьована. Надішліть запит знову.",
        "assistant_busy": "Кілька звернень уже в черзі. Звичайні команди працюють.",
        "assistant_job_expired": "Час очікування звернення минув. Нічого не "
        "виконано. Надішліть запит знову.",
    },
}
