/* Localized copy for explicit, transient public article reading. */

export const ARTICLE_COPY = {
  en: {
    title: "Read a public article",
    open: "Read a public article",
    url: "Public HTTPS page",
    url_hint: "No login, PDF, page JavaScript, or private/local address.",
    review: "Review article request",
    review_title: "Review public article request",
    disclosure:
      "The Home Assistant server will contact this site, which sees the server IP. Extracted page text is sent to the configured primary or fallback model without family context.",
    confirm: "I reviewed this exact public page request",
    fetch: "Fetch and summarize article",
    retry: "Retry exact request",
    back: "Back",
    cancel: "Cancel",
    close: "Clear article result",
    loading: "Fetching and summarizing the public page…",
    result: "Article summary",
    source: "Verified source",
    requested: "Requested page",
    retrieved: "Retrieved",
    disabled: "Public article reading is disabled by the household owner.",
    unavailable: "Configure the Conversation model before reading public articles.",
    not_allowed: "Public article reading is not available for this account.",
  },
  ru: {
    title: "Прочитать публичную статью",
    open: "Прочитать публичную статью",
    url: "Публичная HTTPS-страница",
    url_hint: "Без входа, PDF, JavaScript страницы и частных или локальных адресов.",
    review: "Проверить запрос статьи",
    review_title: "Проверка запроса публичной статьи",
    disclosure:
      "Сервер Home Assistant обратится к сайту, и сайт увидит IP-адрес сервера. Извлечённый текст страницы будет отправлен настроенной основной или резервной модели без семейного контекста.",
    confirm: "Я проверил(а) запрос именно этой публичной страницы",
    fetch: "Загрузить и кратко изложить статью",
    retry: "Повторить точный запрос",
    back: "Назад",
    cancel: "Отмена",
    close: "Очистить результат статьи",
    loading: "Загружаю и кратко излагаю публичную страницу…",
    result: "Краткое изложение статьи",
    source: "Проверенный источник",
    requested: "Запрошенная страница",
    retrieved: "Получено",
    disabled: "Чтение публичных статей отключено владельцем семьи.",
    unavailable: "Настройте модель разговорного помощника для чтения публичных статей.",
    not_allowed: "Чтение публичных статей недоступно для этой учётной записи.",
  },
  uk: {
    title: "Прочитати публічну статтю",
    open: "Прочитати публічну статтю",
    url: "Публічна HTTPS-сторінка",
    url_hint: "Без входу, PDF, JavaScript сторінки та приватних або локальних адрес.",
    review: "Перевірити запит статті",
    review_title: "Перевірка запиту публічної статті",
    disclosure:
      "Сервер Home Assistant звернеться до сайту, і сайт побачить IP-адресу сервера. Витягнутий текст сторінки буде надіслано налаштованій основній або резервній моделі без сімейного контексту.",
    confirm: "Я перевірив(-ла) запит саме цієї публічної сторінки",
    fetch: "Завантажити й стисло викласти статтю",
    retry: "Повторити точний запит",
    back: "Назад",
    cancel: "Скасувати",
    close: "Очистити результат статті",
    loading: "Завантажую й стисло викладаю публічну сторінку…",
    result: "Стислий виклад статті",
    source: "Перевірене джерело",
    requested: "Запитана сторінка",
    retrieved: "Отримано",
    disabled: "Читання публічних статей вимкнено власником родини.",
    unavailable: "Налаштуйте модель розмовного помічника для читання публічних статей.",
    not_allowed: "Читання публічних статей недоступне для цього облікового запису.",
  },
};
