/* Local copy for private, manually recorded dietary preferences. */

export const DIETARY_COPY = {
  en: {
    title: "Dietary preferences",
    help: "These are manually entered notes, not a safety assessment. Check ingredients and product labels yourself. They are not automatically included in AI, search, Telegram, entities, or shopping views.",
    your_profile: "Your preferences",
    managed_children: "Children managed by parents",
    shared_adults: "Adults sharing with parents",
    family_member: "Family member",
    likes: "Likes",
    dislikes: "Dislikes",
    avoid: "Avoid",
    allergy_note: "Allergy note",
    none: "None recorded",
    status_missing: "No profile recorded",
    status_active: "Active",
    status_cleared: "Profile content cleared",
    edit: "Edit preferences",
    review: "Review changes",
    confirm_save: "I reviewed this member and every value above",
    save_title: "Review dietary preferences",
    share: "Share with other parents",
    stop_sharing: "Revoke sharing",
    share_title: "Review parent access",
    share_next: "Parents will be able to read this profile in Family Assistant.",
    revoke_next: "This profile will be removed from parents' Family Assistant view.",
    confirm_share: "I explicitly consent to sharing this profile with parents",
    confirm_revoke: "I explicitly want to revoke parent access",
    shared: "Shared with parents",
    not_shared: "Not shared with parents",
    clear: "Clear profile",
    clear_title: "Clear dietary profile?",
    clear_hint: "This removes the current profile content and leaves a cleared record.",
    confirm_clear: "I reviewed the member and want to clear this profile",
    read_only: "Read-only",
    save: "Save",
    confirm: "Confirm",
    retry: "Retry exact request",
    cancel: "Cancel",
    line_hint: "Enter one item per line.",
    invalid: "Check the lists and note. Each list allows 30 entries of up to 80 characters; labels must be unique across all three lists. The note allows 1000 characters.",
  },
  ru: {
    title: "Пищевые предпочтения",
    help: "Это внесённые вручную заметки, а не оценка безопасности. Самостоятельно проверяйте ингредиенты и этикетки. Данные не включаются автоматически в ИИ, поиск, Telegram, сущности или представления покупок.",
    your_profile: "Ваши предпочтения",
    managed_children: "Дети под управлением родителей",
    shared_adults: "Взрослые, открывшие доступ родителям",
    family_member: "Участник семьи",
    likes: "Люблю",
    dislikes: "Не люблю",
    avoid: "Избегаю",
    allergy_note: "Заметка об аллергии",
    none: "Ничего не указано",
    status_missing: "Профиль не заполнен",
    status_active: "Активен",
    status_cleared: "Содержимое профиля очищено",
    edit: "Изменить предпочтения",
    review: "Проверить изменения",
    confirm_save: "Я проверил(а) участника и все значения выше",
    save_title: "Проверка пищевых предпочтений",
    share: "Поделиться с другими родителями",
    stop_sharing: "Отозвать доступ",
    share_title: "Проверка доступа родителей",
    share_next: "Родители смогут читать этот профиль в Family Assistant.",
    revoke_next: "Профиль исчезнет из родительского представления Family Assistant.",
    confirm_share: "Я явно соглашаюсь открыть этот профиль родителям",
    confirm_revoke: "Я явно хочу отозвать доступ родителей",
    shared: "Доступен родителям",
    not_shared: "Не доступен родителям",
    clear: "Очистить профиль",
    clear_title: "Очистить пищевой профиль?",
    clear_hint: "Текущее содержимое профиля будет удалено, а запись об очистке сохранится.",
    confirm_clear: "Я проверил(а) участника и хочу очистить этот профиль",
    read_only: "Только чтение",
    save: "Сохранить",
    confirm: "Подтвердить",
    retry: "Повторить тот же запрос",
    cancel: "Отмена",
    line_hint: "Одна позиция на строку.",
    invalid: "Проверьте списки и заметку. В каждом списке допускается 30 значений длиной до 80 символов; названия не должны повторяться во всех трёх списках. В заметке допускается до 1000 символов.",
  },
  uk: {
    title: "Харчові вподобання",
    help: "Це внесені вручну примітки, а не оцінка безпеки. Самостійно перевіряйте інгредієнти й етикетки. Дані не додаються автоматично до ШІ, пошуку, Telegram, сутностей або представлень покупок.",
    your_profile: "Ваші вподобання",
    managed_children: "Діти під керуванням батьків",
    shared_adults: "Дорослі, які відкрили доступ батькам",
    family_member: "Учасник родини",
    likes: "Подобається",
    dislikes: "Не подобається",
    avoid: "Уникаю",
    allergy_note: "Нотатка про алергію",
    none: "Нічого не зазначено",
    status_missing: "Профіль не заповнено",
    status_active: "Активний",
    status_cleared: "Вміст профілю очищено",
    edit: "Змінити вподобання",
    review: "Перевірити зміни",
    confirm_save: "Я перевірив(ла) учасника й усі значення вище",
    save_title: "Перевірка харчових уподобань",
    share: "Поділитися з іншими батьками",
    stop_sharing: "Відкликати доступ",
    share_title: "Перевірка доступу батьків",
    share_next: "Батьки зможуть читати цей профіль у Family Assistant.",
    revoke_next: "Профіль зникне з батьківського представлення Family Assistant.",
    confirm_share: "Я явно погоджуюся відкрити цей профіль батькам",
    confirm_revoke: "Я явно хочу відкликати доступ батьків",
    shared: "Доступний батькам",
    not_shared: "Не доступний батькам",
    clear: "Очистити профіль",
    clear_title: "Очистити харчовий профіль?",
    clear_hint: "Поточний вміст профілю буде видалено, а запис про очищення збережеться.",
    confirm_clear: "Я перевірив(ла) учасника й хочу очистити цей профіль",
    read_only: "Лише читання",
    save: "Зберегти",
    confirm: "Підтвердити",
    retry: "Повторити той самий запит",
    cancel: "Скасувати",
    line_hint: "Одна позиція на рядок.",
    invalid: "Перевірте списки й примітку. У кожному списку дозволено 30 значень завдовжки до 80 символів; назви не мають повторюватися в усіх трьох списках. У примітці дозволено до 1000 символів.",
  },
};
