/* Localized copy for self-consented, private family digest controls. */

export const DIGESTS_COPY = {
  en: {
    guide: "How private digests work",
    help: "Each digest is built for you from information you can currently open. Counts can still reveal personal information; they are minimized, not anonymous.",
    delivery:
      "A saved preference permits delivery only to your current private Telegram chat when the owner policy is also enabled. Preview stays on this screen and is not sent.",
    no_effects:
      "Digests do not use a language model or search, and never change tasks, routines, shopping, points, devices, alarms, or presence.",
    options_help:
      "The household owner controls schedules and the household time zone in integration Settings. This card changes only your preferences.",
    global_policy: "Owner delivery policy",
    timezone: "Household time zone",
    morning: "Morning",
    evening: "Evening",
    weekly: "Weekly",
    enabled: "Enabled",
    disabled: "Disabled",
    at: "at",
    weekday: "weekday",
    day_0: "Monday",
    day_1: "Tuesday",
    day_2: "Wednesday",
    day_3: "Thursday",
    day_4: "Friday",
    day_5: "Saturday",
    day_6: "Sunday",
    your_preferences: "Your digest preferences",
    delivery_health: "Delivery status",
    health_ok: "No current delivery issue",
    health_attention: "Needs attention in delivery health",
    change: "Change preferences",
    preference_off_hint:
      "You can save a preference while an owner policy is off; it will not schedule delivery until that policy is enabled.",
    edit_title: "Choose your private digests",
    continue: "Review preferences",
    review_title: "Review digest preferences",
    person: "Family member",
    recipient_version: "Member version",
    subscription_version: "Preference version",
    absent: "not created",
    confirm:
      "I checked the named family member and understand that these private summaries may contain personal information visible to my current Home Assistant account.",
    save: "Save digest preferences",
    retry: "Retry exact request",
    cancel: "Cancel",
    choose_one: "Choose at least one digest for a new preference.",
    no_changes: "Change at least one preference before review.",
    unavailable_action:
      "Your current linked family profile cannot change digest preferences.",
    preview_title: "Private preview",
    preview_help:
      "Request a fresh preview explicitly. It uses the current household date window, is not a sent message, and is not a history view.",
    preview_kind: "Digest to preview",
    preview: "Build private preview",
    loading: "Building preview…",
    preview_window: "Window",
    empty_preview: "Nothing is available for this preview window.",
    items: "items",
    more: "more not shown",
    tasks: "Tasks",
    calendar: "Calendar",
    routines: "Routines",
    school: "School",
    shopping: "Open shopping",
    pantry_low_stock: "Low-stock items",
    pantry_expiring: "Items nearing recorded expiry",
    maintenance_faults: "Open maintenance faults",
    maintenance_services: "Maintenance services",
    polls_open: "Open polls",
    polls_results: "Available poll results",
    task_status: "Status",
    due: "Due",
    all_day: "All day",
    materials: "Materials",
    unavailable_member: "Current family member",
    invalid_preview: "The private preview could not be loaded safely.",
  },
  ru: {
    guide: "Как работают личные дайджесты",
    help: "Каждый дайджест составляется для вас только из данных, которые вы сейчас вправе открыть. Даже счётчики могут раскрывать личную информацию: они сокращены, но не анонимны.",
    delivery:
      "Сохранённая настройка разрешает отправку только в ваш текущий личный чат Telegram и только при включённой политике владельца. Предпросмотр остаётся на этом экране и не отправляется.",
    no_effects:
      "Дайджесты не используют языковую модель или поиск и не меняют задачи, рутины, покупки, баллы, устройства, будильники или присутствие.",
    options_help:
      "Расписание и часовой пояс семьи задаёт владелец в настройках интеграции. Эта карточка меняет только ваши предпочтения.",
    global_policy: "Политика отправки владельца",
    timezone: "Часовой пояс семьи",
    morning: "Утренний",
    evening: "Вечерний",
    weekly: "Еженедельный",
    enabled: "Включён",
    disabled: "Выключен",
    at: "в",
    weekday: "день недели",
    day_0: "понедельник",
    day_1: "вторник",
    day_2: "среда",
    day_3: "четверг",
    day_4: "пятница",
    day_5: "суббота",
    day_6: "воскресенье",
    your_preferences: "Ваши настройки дайджестов",
    delivery_health: "Состояние доставки",
    health_ok: "Сейчас проблем доставки нет",
    health_attention: "Нужно проверить состояние доставки",
    change: "Изменить настройки",
    preference_off_hint:
      "Настройку можно сохранить, пока политика владельца выключена; отправка начнётся только после её включения.",
    edit_title: "Выберите личные дайджесты",
    continue: "Проверить настройки",
    review_title: "Проверка настроек дайджестов",
    person: "Участник семьи",
    recipient_version: "Версия участника",
    subscription_version: "Версия настройки",
    absent: "ещё не создана",
    confirm:
      "Я проверил(а) указанного участника и понимаю, что эти личные сводки могут содержать персональные данные, доступные моей текущей учётной записи Home Assistant.",
    save: "Сохранить настройки дайджестов",
    retry: "Повторить точный запрос",
    cancel: "Отмена",
    choose_one: "Для новой настройки выберите хотя бы один дайджест.",
    no_changes: "Перед проверкой измените хотя бы одну настройку.",
    unavailable_action:
      "Текущий связанный профиль семьи не может менять настройки дайджестов.",
    preview_title: "Личный предпросмотр",
    preview_help:
      "Запросите свежий предпросмотр явно. Он использует текущий семейный период, не является отправленным сообщением и не показывает историю.",
    preview_kind: "Дайджест для предпросмотра",
    preview: "Создать личный предпросмотр",
    loading: "Создаётся предпросмотр…",
    preview_window: "Период",
    empty_preview: "Для этого периода доступных данных нет.",
    items: "элементов",
    more: "ещё не показано",
    tasks: "Задачи",
    calendar: "Календарь",
    routines: "Рутины",
    school: "Школа",
    shopping: "Открытые покупки",
    pantry_low_stock: "Товары с малым запасом",
    pantry_expiring: "Товары с близким записанным сроком",
    maintenance_faults: "Открытые неисправности",
    maintenance_services: "Обслуживание",
    polls_open: "Открытые голосования",
    polls_results: "Доступные итоги голосований",
    task_status: "Статус",
    due: "Срок",
    all_day: "Весь день",
    materials: "Материалы",
    unavailable_member: "Текущий участник семьи",
    invalid_preview: "Не удалось безопасно загрузить личный предпросмотр.",
  },
  uk: {
    guide: "Як працюють особисті дайджести",
    help: "Кожен дайджест складається для вас лише з даних, які ви зараз маєте право відкрити. Навіть лічильники можуть розкривати особисту інформацію: вони мінімізовані, але не анонімні.",
    delivery:
      "Збережене налаштування дозволяє надсилання лише до вашого поточного приватного чату Telegram і лише за ввімкненої політики власника. Попередній перегляд залишається на цьому екрані й не надсилається.",
    no_effects:
      "Дайджести не використовують мовну модель чи пошук і не змінюють завдання, рутини, покупки, бали, пристрої, будильники або присутність.",
    options_help:
      "Розклад і часовий пояс родини задає власник у налаштуваннях інтеграції. Ця картка змінює лише ваші вподобання.",
    global_policy: "Політика надсилання власника",
    timezone: "Часовий пояс родини",
    morning: "Ранковий",
    evening: "Вечірній",
    weekly: "Щотижневий",
    enabled: "Увімкнений",
    disabled: "Вимкнений",
    at: "о",
    weekday: "день тижня",
    day_0: "понеділок",
    day_1: "вівторок",
    day_2: "середа",
    day_3: "четвер",
    day_4: "п’ятниця",
    day_5: "субота",
    day_6: "неділя",
    your_preferences: "Ваші налаштування дайджестів",
    delivery_health: "Стан доставки",
    health_ok: "Зараз проблем із доставкою немає",
    health_attention: "Потрібно перевірити стан доставки",
    change: "Змінити налаштування",
    preference_off_hint:
      "Налаштування можна зберегти, поки політика власника вимкнена; надсилання почнеться лише після її ввімкнення.",
    edit_title: "Виберіть особисті дайджести",
    continue: "Перевірити налаштування",
    review_title: "Перевірка налаштувань дайджестів",
    person: "Член родини",
    recipient_version: "Версія учасника",
    subscription_version: "Версія налаштування",
    absent: "ще не створена",
    confirm:
      "Я перевірив(-ла) вказаного учасника й розумію, що ці особисті зведення можуть містити персональні дані, доступні моєму поточному обліковому запису Home Assistant.",
    save: "Зберегти налаштування дайджестів",
    retry: "Повторити точний запит",
    cancel: "Скасувати",
    choose_one: "Для нового налаштування виберіть хоча б один дайджест.",
    no_changes: "Перед перевіркою змініть хоча б одне налаштування.",
    unavailable_action:
      "Поточний пов’язаний профіль родини не може змінювати налаштування дайджестів.",
    preview_title: "Особистий попередній перегляд",
    preview_help:
      "Запросіть свіжий попередній перегляд явно. Він використовує поточний родинний період, не є надісланим повідомленням і не показує історію.",
    preview_kind: "Дайджест для попереднього перегляду",
    preview: "Створити особистий перегляд",
    loading: "Створюється перегляд…",
    preview_window: "Період",
    empty_preview: "Для цього періоду доступних даних немає.",
    items: "елементів",
    more: "ще не показано",
    tasks: "Завдання",
    calendar: "Календар",
    routines: "Рутини",
    school: "Школа",
    shopping: "Відкриті покупки",
    pantry_low_stock: "Позиції з малим запасом",
    pantry_expiring: "Позиції з близьким записаним строком",
    maintenance_faults: "Відкриті несправності",
    maintenance_services: "Обслуговування",
    polls_open: "Відкриті голосування",
    polls_results: "Доступні підсумки голосувань",
    task_status: "Статус",
    due: "Строк",
    all_day: "Увесь день",
    materials: "Матеріали",
    unavailable_member: "Поточний член родини",
    invalid_preview: "Не вдалося безпечно завантажити особистий перегляд.",
  },
};
