/* Local copy for reviewed household maintenance records. */

export const MAINTENANCE_COPY = {
  en: {
    title: "Home maintenance",
    help: "Record equipment, faults, planned service, and completed work.",
    parent_help: "Parents manage full maintenance records. Other family members can report faults for equipment assigned to them or enabled for reporting by a parent.",
    limited_help: "You see active equipment enabled for your reports, assigned to you, or linked to your own maintenance task. Fault reports are limited to ones you reported or were assigned.",
    timezone: "Household time zone",
    safety_note: "These are household records, not a safety inspection or certification.",
    schedule_note: "Service schedules use tasks for reminders and completion. They do not start physical work or order supplies.",
    privacy_note: "Notes can contain household details. Review them before saving.",
    attachments_unavailable: "Photo and document upload is not available in this card. Describe the issue in text.",
    assets: "Equipment",
    no_assets: "No equipment recorded.",
    active_faults: "Fault reports",
    no_faults: "No visible fault reports.",
    services: "Service schedules",
    no_services: "No service schedules recorded.",
    service_history: "Completed service records",
    no_service_history: "No completed service records.",
    asset_name: "Equipment name",
    category: "Category",
    location: "Location",
    responsible: "Responsible family member",
    warranty: "Warranty",
    warranty_expires: "Warranty expires",
    vendor: "Vendor",
    reference: "Reference",
    consumables: "Consumables",
    consumable_label: "Consumable",
    reportable: "Allow family fault reports",
    add_consumable: "Add consumable",
    remove_consumable: "Remove consumable",
    unit: "Unit",
    quantity: "Quantity",
    pantry_item: "Pantry item (optional)",
    pantry_hint: "Pantry links are informational. Saving records does not deduct stock or order supplies.",
    pantry_unavailable: "Unavailable saved pantry link",
    pantry_unavailable_hint: "Explicitly choose no pantry item or a current item with the same unit before reviewing.",
    note: "Private maintenance note",
    status_active: "Active",
    status_retired: "Retired",
    new_asset: "Add equipment",
    edit_asset: "Edit equipment",
    retire_asset: "Retire equipment",
    retire_reason: "Retirement reason",
    report_fault: "Report a fault",
    reporter: "Reported by",
    reported_at: "Reported",
    fault_summary: "Short summary",
    fault_details: "What was observed",
    linked_task: "Linked task",
    manual_service_log: "Record completed service",
    performed_on: "Performed on",
    service_summary: "Work performed",
    service_task: "Related task (optional)",
    consumables_used: "Consumables used",
    new_service: "Add service schedule",
    edit_service: "Edit service schedule",
    service_title: "Service title",
    assignees: "Assigned family members",
    assignee_unavailable: "Unavailable saved assignee",
    assignee_unavailable_hint: "Choose current assignees and explicitly confirm replacing unavailable assignees.",
    confirm_assignee_replacement: "I reviewed and replaced the unavailable assignees",
    rotation: "Assignment rotation",
    rotation_hint: "Assign each occurrence to one person in rotation",
    recurrence: "Schedule",
    due_time: "Due time",
    checklist: "Checklist",
    checklist_hint: "One step per line; up to 50.",
    enabled: "Enabled",
    disabled: "Disabled",
    reminder_minutes: "Reminder before due time (minutes)",
    grace_minutes: "Grace after due time (minutes)",
    enable_service: "Enable schedule",
    disable_service: "Disable schedule",
    current_warning: "This saved link is no longer current. Review and replace the stale fields before saving.",
    review_asset: "Review exact equipment record",
    review_fault: "Review exact fault report",
    review_log: "Review exact completed service",
    review_service: "Review exact service schedule",
    review_retire: "Review equipment retirement",
    review_toggle: "Review schedule status change",
    confirm_asset: "I checked the equipment, responsible member, warranty, consumables, and note",
    confirm_fault: "I checked the equipment and the exact fault description",
    confirm_log: "I checked the date, completed work, task link, and consumables used",
    confirm_service: "I checked the equipment, assignees, schedule, time, checklist, and reminder settings",
    confirm_retire: "I checked the equipment and want to retire this record",
    confirm_toggle: "I checked the schedule and the requested status",
    save: "Save",
    retire: "Retire",
    submit_report: "Submit fault report",
    record_service: "Record service",
    retry_exact: "Retry exact request",
    retry_hint: "The result is unconfirmed. Retry sends the same reviewed request and operation ID.",
    cancel: "Cancel",
    history: "History",
    action_created: "Created",
    action_updated: "Updated",
    action_retired: "Retired",
    revision: "version",
    invalid: "Check every required field, date, quantity, family member, link, and schedule value.",
    stale: "The record, family access, or configuration changed. Start again from the current data.",
    unknown_member: "Family member",
    none: "None",
  },
  ru: {
    title: "Обслуживание дома",
    help: "Ведите учёт оборудования, неисправностей, плановых и выполненных работ.",
    parent_help: "Родители управляют полными записями. Другие участники семьи могут сообщать только об оборудовании, закреплённом за ними или открытом родителем для сообщений.",
    limited_help: "Вам видно активное оборудование, открытое для ваших сообщений, закреплённое за вами или связанное с вашей задачей. Сообщения ограничены созданными вами или назначенными вам.",
    timezone: "Часовой пояс семьи",
    safety_note: "Это семейные записи, а не проверка или подтверждение безопасности.",
    schedule_note: "Для напоминаний и завершения регламент использует задачи. Он не запускает физические работы и не заказывает расходники.",
    privacy_note: "Заметки могут содержать сведения о доме. Проверьте их перед сохранением.",
    attachments_unavailable: "Загрузка фото и документов в этой карточке недоступна. Опишите неисправность текстом.",
    assets: "Оборудование",
    no_assets: "Оборудование пока не добавлено.",
    active_faults: "Сообщения о неисправностях",
    no_faults: "Нет доступных сообщений о неисправностях.",
    services: "Регламентные работы",
    no_services: "Регламентные работы пока не настроены.",
    service_history: "История выполненных работ",
    no_service_history: "Выполненных работ пока нет.",
    asset_name: "Название оборудования",
    category: "Категория",
    location: "Место",
    responsible: "Ответственный участник семьи",
    warranty: "Гарантия",
    warranty_expires: "Гарантия до",
    vendor: "Продавец или сервис",
    reference: "Ссылка или номер",
    consumables: "Расходники",
    consumable_label: "Расходник",
    reportable: "Разрешить семье сообщать о неисправностях",
    add_consumable: "Добавить расходник",
    remove_consumable: "Удалить расходник",
    unit: "Единица",
    quantity: "Количество",
    pantry_item: "Позиция в запасах (необязательно)",
    pantry_hint: "Связи с запасами носят справочный характер. Сохранение записей не списывает запасы и не заказывает расходники.",
    pantry_unavailable: "Недоступная сохранённая связь с запасами",
    pantry_unavailable_hint: "Перед проверкой явно выберите вариант без связи или актуальную позицию с той же единицей.",
    note: "Закрытая заметка об обслуживании",
    status_active: "Активно",
    status_retired: "Снято с учёта",
    new_asset: "Добавить оборудование",
    edit_asset: "Изменить оборудование",
    retire_asset: "Снять оборудование с учёта",
    retire_reason: "Причина снятия с учёта",
    report_fault: "Сообщить о неисправности",
    reporter: "Сообщил(а)",
    reported_at: "Дата сообщения",
    fault_summary: "Краткое описание",
    fault_details: "Что было замечено",
    linked_task: "Связанная задача",
    manual_service_log: "Записать выполненную работу",
    performed_on: "Дата выполнения",
    service_summary: "Что было сделано",
    service_task: "Связанная задача (необязательно)",
    consumables_used: "Использованные расходники",
    new_service: "Добавить регламент",
    edit_service: "Изменить регламент",
    service_title: "Название работы",
    assignees: "Ответственные участники семьи",
    assignee_unavailable: "Недоступный сохранённый ответственный",
    assignee_unavailable_hint: "Выберите актуальных ответственных и явно подтвердите замену недоступных.",
    confirm_assignee_replacement: "Я проверил(а) и заменил(а) недоступных ответственных",
    rotation: "Чередование ответственных",
    rotation_hint: "Назначать каждое выполнение одному человеку по очереди",
    recurrence: "Расписание",
    due_time: "Время выполнения",
    checklist: "Чек-лист",
    checklist_hint: "Один шаг на строку; не более 50.",
    enabled: "Включено",
    disabled: "Выключено",
    reminder_minutes: "Напомнить до срока (минуты)",
    grace_minutes: "Допустимая задержка после срока (минуты)",
    enable_service: "Включить регламент",
    disable_service: "Выключить регламент",
    current_warning: "Сохранённая связь устарела. Проверьте и замените устаревшие поля перед сохранением.",
    review_asset: "Проверить точную запись об оборудовании",
    review_fault: "Проверить точное сообщение о неисправности",
    review_log: "Проверить точную запись о выполненной работе",
    review_service: "Проверить точный регламент",
    review_retire: "Проверить снятие оборудования с учёта",
    review_toggle: "Проверить изменение состояния регламента",
    confirm_asset: "Я проверил(а) оборудование, ответственного, гарантию, расходники и заметку",
    confirm_fault: "Я проверил(а) оборудование и точное описание неисправности",
    confirm_log: "Я проверил(а) дату, выполненную работу, связанную задачу и использованные расходники",
    confirm_service: "Я проверил(а) оборудование, ответственных, расписание, время, чек-лист и напоминания",
    confirm_retire: "Я проверил(а) оборудование и хочу снять эту запись с учёта",
    confirm_toggle: "Я проверил(а) регламент и выбранное состояние",
    save: "Сохранить",
    retire: "Снять с учёта",
    submit_report: "Отправить сообщение",
    record_service: "Записать работу",
    retry_exact: "Повторить точный запрос",
    retry_hint: "Результат не подтверждён. Повтор отправит тот же проверенный запрос с тем же идентификатором операции.",
    cancel: "Отмена",
    history: "История",
    action_created: "Создано",
    action_updated: "Изменено",
    action_retired: "Снято с учёта",
    revision: "версия",
    invalid: "Проверьте обязательные поля, даты, количества, участников, связи и расписание.",
    stale: "Запись, доступ семьи или настройки изменились. Начните заново с актуальных данных.",
    unknown_member: "Участник семьи",
    none: "Нет",
  },
  uk: {
    title: "Обслуговування дому",
    help: "Ведіть облік обладнання, несправностей, планових і виконаних робіт.",
    parent_help: "Батьки керують повними записами. Інші члени родини можуть повідомляти лише про обладнання, закріплене за ними або відкрите батьками для повідомлень.",
    limited_help: "Вам видно активне обладнання, відкрите для ваших повідомлень, закріплене за вами або пов’язане з вашим завданням. Повідомлення обмежені створеними вами або призначеними вам.",
    timezone: "Часовий пояс родини",
    safety_note: "Це родинні записи, а не перевірка чи підтвердження безпеки.",
    schedule_note: "Для нагадувань і завершення регламент використовує завдання. Він не запускає фізичні роботи й не замовляє витратні матеріали.",
    privacy_note: "Нотатки можуть містити відомості про оселю. Перевірте їх перед збереженням.",
    attachments_unavailable: "Завантаження фото й документів у цій картці недоступне. Опишіть несправність текстом.",
    assets: "Обладнання",
    no_assets: "Обладнання ще не додано.",
    active_faults: "Повідомлення про несправності",
    no_faults: "Немає доступних повідомлень про несправності.",
    services: "Регламентні роботи",
    no_services: "Регламентні роботи ще не налаштовано.",
    service_history: "Історія виконаних робіт",
    no_service_history: "Виконаних робіт ще немає.",
    asset_name: "Назва обладнання",
    category: "Категорія",
    location: "Місце",
    responsible: "Відповідальний член родини",
    warranty: "Гарантія",
    warranty_expires: "Гарантія до",
    vendor: "Продавець або сервіс",
    reference: "Посилання або номер",
    consumables: "Витратні матеріали",
    consumable_label: "Витратний матеріал",
    reportable: "Дозволити родині повідомляти про несправності",
    add_consumable: "Додати витратний матеріал",
    remove_consumable: "Видалити витратний матеріал",
    unit: "Одиниця",
    quantity: "Кількість",
    pantry_item: "Позиція в запасах (необов’язково)",
    pantry_hint: "Зв’язки із запасами мають довідковий характер. Збереження записів не списує запаси й не замовляє витратні матеріали.",
    pantry_unavailable: "Недоступний збережений зв’язок із запасами",
    pantry_unavailable_hint: "Перед перевіркою явно виберіть варіант без зв’язку або актуальну позицію з тією самою одиницею.",
    note: "Закрита нотатка про обслуговування",
    status_active: "Активне",
    status_retired: "Знято з обліку",
    new_asset: "Додати обладнання",
    edit_asset: "Змінити обладнання",
    retire_asset: "Зняти обладнання з обліку",
    retire_reason: "Причина зняття з обліку",
    report_fault: "Повідомити про несправність",
    reporter: "Повідомив(ла)",
    reported_at: "Дата повідомлення",
    fault_summary: "Короткий опис",
    fault_details: "Що було помічено",
    linked_task: "Пов’язане завдання",
    manual_service_log: "Записати виконану роботу",
    performed_on: "Дата виконання",
    service_summary: "Що було зроблено",
    service_task: "Пов’язане завдання (необов’язково)",
    consumables_used: "Використані витратні матеріали",
    new_service: "Додати регламент",
    edit_service: "Змінити регламент",
    service_title: "Назва роботи",
    assignees: "Відповідальні члени родини",
    assignee_unavailable: "Недоступний збережений відповідальний",
    assignee_unavailable_hint: "Виберіть актуальних відповідальних і явно підтвердьте заміну недоступних.",
    confirm_assignee_replacement: "Я перевірив(ла) й замінив(ла) недоступних відповідальних",
    rotation: "Чергування відповідальних",
    rotation_hint: "Призначати кожне виконання одній людині по черзі",
    recurrence: "Розклад",
    due_time: "Час виконання",
    checklist: "Чек-лист",
    checklist_hint: "Один крок на рядок; не більше 50.",
    enabled: "Увімкнено",
    disabled: "Вимкнено",
    reminder_minutes: "Нагадати до строку (хвилини)",
    grace_minutes: "Допустима затримка після строку (хвилини)",
    enable_service: "Увімкнути регламент",
    disable_service: "Вимкнути регламент",
    current_warning: "Збережений зв’язок застарів. Перевірте й замініть застарілі поля перед збереженням.",
    review_asset: "Перевірити точний запис про обладнання",
    review_fault: "Перевірити точне повідомлення про несправність",
    review_log: "Перевірити точний запис про виконану роботу",
    review_service: "Перевірити точний регламент",
    review_retire: "Перевірити зняття обладнання з обліку",
    review_toggle: "Перевірити зміну стану регламенту",
    confirm_asset: "Я перевірив(ла) обладнання, відповідального, гарантію, витратні матеріали й нотатку",
    confirm_fault: "Я перевірив(ла) обладнання й точний опис несправності",
    confirm_log: "Я перевірив(ла) дату, виконану роботу, пов’язане завдання та використані витратні матеріали",
    confirm_service: "Я перевірив(ла) обладнання, відповідальних, розклад, час, чек-лист і нагадування",
    confirm_retire: "Я перевірив(ла) обладнання й хочу зняти цей запис з обліку",
    confirm_toggle: "Я перевірив(ла) регламент і вибраний стан",
    save: "Зберегти",
    retire: "Зняти з обліку",
    submit_report: "Надіслати повідомлення",
    record_service: "Записати роботу",
    retry_exact: "Повторити точний запит",
    retry_hint: "Результат не підтверджено. Повтор надішле той самий перевірений запит із тим самим ідентифікатором операції.",
    cancel: "Скасувати",
    history: "Історія",
    action_created: "Створено",
    action_updated: "Змінено",
    action_retired: "Знято з обліку",
    revision: "версія",
    invalid: "Перевірте обов’язкові поля, дати, кількості, учасників, зв’язки й розклад.",
    stale: "Запис, доступ родини або налаштування змінилися. Почніть знову з актуальних даних.",
    unknown_member: "Член родини",
    none: "Немає",
  },
};
