/* Local meals copy for Family Assistant card. */

export const MEALS_COPY = {
  en: {
    title: "Meal Plan",
    new_plan: "New plan",
    edit: "Edit plan",
    publish: "Publish plan",
    archive: "Archive plan",
    save: "Save",
    cancel: "Cancel",
    retry: "Retry",
    week_start: "Week starting (Monday)",
    plan_title: "Plan title",
    note: "Parent note",
    entries: "Planned meals",
    add_meal: "Add meal",
    remove_meal: "Remove meal",
    date: "Date",
    slot: "Meal slot",
    meal_title: "Meal name",
    servings: "Servings",
    ingredients: "Ingredients",
    add_ingredient: "Add ingredient",
    remove_ingredient: "Remove ingredient",
    name: "Ingredient name",
    unit: "Unit of measurement",
    quantity: "Total quantity",
    reason: "Reason for change",
    draft: "Draft",
    published: "Published",
    archived: "Archived",
    empty: "No meal plans yet.",
    no_published: "No published meal plans.",
    help: "Weekly meal menu planned by parents. Parents create draft plans and explicitly publish them; children and adult members can only view published plans. Only parents have access to private notes and plan history. There is one published plan per Monday week, and editing a published plan returns it to draft status.",
    totals_hint:
      "Ingredient quantities represent the manual total needed for the specified servings. Quantities are never auto-scaled, converted, or checked against allergies.",
    private_hint:
      "Meal plan notes and revision history are private to parents and are not shown to other family members.",
    publish_hint:
      "Publishing shares the menu with active family members except guests. Only one plan can be published per Monday week.",
    edit_hint:
      "Editing a published plan returns it to draft status until explicitly republished by a parent.",
    manual_hint:
      "Meal planning does not automatically deduct pantry stock or create shopping orders.",
    history: "Plan history",
    history_created: "Created",
    history_edited: "Edited",
    history_published: "Published",
    history_archived: "Archived",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snack",
    module_off: "Enable Pantry & household stock to use meal plans.",
    review_publish: "Publish this meal plan for the family?",
    review_archive: "Archive this meal plan?",
  },
  ru: {
    title: "План питания",
    new_plan: "Новый план",
    edit: "Редактировать план",
    publish: "Опубликовать план",
    archive: "Архивировать план",
    save: "Сохранить",
    cancel: "Отмена",
    retry: "Повторить",
    week_start: "Начало недели (понедельник)",
    plan_title: "Название плана",
    note: "Заметка для родителей",
    entries: "Запланированные приёмы пищи",
    add_meal: "Добавить блюдо",
    remove_meal: "Удалить блюдо",
    date: "Дата",
    slot: "Приём пищи",
    meal_title: "Название блюда",
    servings: "Порции",
    ingredients: "Ингредиенты",
    add_ingredient: "Добавить ингредиент",
    remove_ingredient: "Удалить ингредиент",
    name: "Название ингредиента",
    unit: "Единица измерения",
    quantity: "Общее количество",
    reason: "Причина изменения",
    draft: "Черновик",
    published: "Опубликован",
    archived: "В архиве",
    empty: "Планов питания пока нет.",
    no_published: "Нет опубликованных планов питания.",
    help: "Еженедельное меню питания, составляемое родителями. Родители создают черновики и явно публикуют их; дети и взрослые участники видят только опубликованные планы. Заметки и история изменений доступны исключительно родителям. На одну неделю с понедельника может быть только один опубликованный план, а редактирование опубликованного плана возвращает его в статус черновика.",
    totals_hint:
      "Количество ингредиентов задаётся вручную как общий объём на указанное число порций. Значения не масштабируются автоматически, не конвертируются и не проверяются на аллергены.",
    private_hint:
      "Заметки к плану и история изменений конфиденциальны, доступны только родителям и скрыты от остальных членов семьи.",
    publish_hint:
      "Меню увидят активные участники семьи, кроме гостей. На одну неделю с понедельника публикуется только один план.",
    edit_hint:
      "Редактирование опубликованного плана возвращает его в статус черновика до повторной публикации родителем.",
    manual_hint:
      "План питания не списывает продукты из кладовой автоматически и не оформляет заказы на покупку.",
    history: "История плана",
    history_created: "Создан",
    history_edited: "Изменён",
    history_published: "Опубликован",
    history_archived: "В архиве",
    breakfast: "Завтрак",
    lunch: "Обед",
    dinner: "Ужин",
    snack: "Перекус",
    module_off: "Для меню включите модуль «Продукты и запасы».",
    review_publish: "Опубликовать этот план питания для семьи?",
    review_archive: "Отправить этот план питания в архив?",
  },
  uk: {
    title: "План харчування",
    new_plan: "Новий план",
    edit: "Редагувати план",
    publish: "Опублікувати план",
    archive: "Архівувати план",
    save: "Зберегти",
    cancel: "Скасувати",
    retry: "Повторити",
    week_start: "Початок тижня (понеділок)",
    plan_title: "Назва плану",
    note: "Примітка для батьків",
    entries: "Заплановані прийоми їжі",
    add_meal: "Додати страву",
    remove_meal: "Видалити страву",
    date: "Дата",
    slot: "Прийом їжі",
    meal_title: "Назва страви",
    servings: "Порції",
    ingredients: "Інгредієнти",
    add_ingredient: "Додати інгредієнт",
    remove_ingredient: "Видалити інгредієнт",
    name: "Назва інгредієнта",
    unit: "Одиниця вимірювання",
    quantity: "Загальна кількість",
    reason: "Причина зміни",
    draft: "Чернетка",
    published: "Опубліковано",
    archived: "В архіві",
    empty: "Планів харчування поки немає.",
    no_published: "Немає опублікованих планів харчування.",
    help: "Щотижневе меню харчування, яке формують батьки. Батьки створюють чернетки та явно публікують їх; діти та дорослі учасники бачать лише опубліковані плани. Примітки та історія змін доступні виключно батькам. На один тиждень із понеділка може бути лише один опублікований план, а редагування опублікованого плану повертає його до статусу чернетки.",
    totals_hint:
      "Кількість інгредієнтів зазначається вручну як загальний обсяг на вказану кількість порцій. Значення ніколи автоматично не масштабуються, не конвертуються і не перевіряються на алергени.",
    private_hint:
      "Примітки до плану та історія змін є конфіденційними, доступні лише батькам і не відображаються іншим членам родини.",
    publish_hint:
      "Меню побачать активні учасники родини, крім гостей. На один тиждень із понеділка публікується лише один план.",
    edit_hint:
      "Редагування опублікованого плану повертає його до статусу чернетки до повторної публікації батьками.",
    manual_hint:
      "Планування харчування не списує залишки в коморі автоматично та не створює замовлень на закупівлю.",
    history: "Історія плану",
    history_created: "Створено",
    history_edited: "Змінено",
    history_published: "Опубліковано",
    history_archived: "В архіві",
    breakfast: "Сніданок",
    lunch: "Обід",
    dinner: "Вечеря",
    snack: "Перекус",
    module_off: "Для меню увімкніть модуль «Продукти й запаси».",
    review_publish: "Опублікувати цей план харчування для родини?",
    review_archive: "Перемістити цей план харчування до архіву?",
  },
};
