/* Control-center copy. Household data never belongs in this catalog. */
const rows = {
  subtitle: ["Together, every day", "Вместе каждый день", "Разом щодня"],
  overview: ["Overview", "Обзор", "Огляд"], members: ["Members", "Участники", "Учасники"],
  modules: ["Capabilities", "Возможности", "Можливості"], connections: ["Connections", "Подключения", "Підключення"],
  advanced: ["Advanced", "Дополнительно", "Додатково"], search: ["Find a setting…", "Найти настройку…", "Знайти налаштування…"],
  noResults: ["No matching settings", "Настройки не найдены", "Налаштувань не знайдено"],
  loading: ["Loading your family…", "Загружаем семью…", "Завантажуємо родину…"],
  noHousehold: ["No linked family. Add Family Assistant or ask the owner to link your HA account.", "Нет связанной семьи. Добавьте Family Assistant или попросите владельца связать вашу учётную запись HA.", "Немає пов’язаної родини. Додайте Family Assistant або попросіть власника прив’язати ваш обліковий запис HA."],
  choose: ["Choose a family", "Выберите семью", "Виберіть родину"], retry: ["Retry", "Повторить", "Повторити"], refresh: ["Refresh", "Обновить", "Оновити"],
  failure: ["Could not complete the request. Try again.", "Не удалось выполнить запрос. Попробуйте снова.", "Не вдалося виконати запит. Спробуйте знову."],
  saved: ["Saved and verified", "Сохранено и проверено", "Збережено й перевірено"],
  unverified: ["Save accepted, but verification failed. Refresh before continuing.", "Сохранение принято, но проверка не удалась. Обновите данные перед продолжением.", "Збереження прийнято, але перевірка не вдалася. Оновіть дані перед продовженням."],
  conflict: ["Settings changed in another window. Your draft is kept; reload before saving.", "Настройки изменились в другом окне. Черновик сохранён; загрузите актуальные данные.", "Налаштування змінилися в іншому вікні. Чернетку збережено; завантажте актуальні дані."],
  discard: ["Discard unsaved changes?", "Отменить несохранённые изменения?", "Скасувати незбережені зміни?"], draft: ["Unsaved changes", "Есть несохранённые изменения", "Є незбережені зміни"],
  save: ["Save", "Сохранить", "Зберегти"], saving: ["Saving…", "Сохраняем…", "Зберігаємо…"], cancel: ["Cancel", "Отмена", "Скасувати"], back: ["Back", "Назад", "Назад"],
  edit: ["Edit", "Изменить", "Змінити"], configure: ["Configure", "Настроить", "Налаштувати"],
  addMember: ["Add member", "Добавить участника", "Додати учасника"], newMember: ["New member", "Новый участник", "Новий учасник"],
  name: ["Name", "Имя", "Ім’я"], familyName: ["Family name", "Название семьи", "Назва родини"], role: ["Family role", "Роль в семье", "Роль у родині"],
  owner: ["Owner", "Владелец", "Власник"], parent: ["Parent", "Родитель", "Батько / мати"], adult: ["Adult", "Взрослый", "Дорослий"], child: ["Child", "Ребёнок", "Дитина"], guest: ["Guest", "Гость", "Гість"],
  language: ["Message language", "Язык сообщений", "Мова повідомлень"], timezone: ["Time zone", "Часовой пояс", "Часовий пояс"],
  aliases: ["Names and nicknames", "Домашние имена и псевдонимы", "Домашні імена та псевдоніми"], aliasesHint: ["Separate names with commas.", "Разделяйте имена запятыми.", "Розділяйте імена комами."],
  accounts: ["Accounts and connections", "Аккаунты и связь", "Облікові записи й зв’язок"], haUser: ["Home Assistant account", "Пользователь Home Assistant", "Користувач Home Assistant"],
  haHint: ["An HA account is optional. Account details are in advanced settings.", "Учётная запись HA необязательна. Подробности — в дополнительных настройках.", "Обліковий запис HA необов’язковий. Подробиці — у додаткових налаштуваннях."],
  userId: ["HA user ID", "ID пользователя HA", "ID користувача HA"], active: ["Active member", "Активный участник", "Активний учасник"], inactive: ["Inactive", "Неактивен", "Неактивний"],
  linked: ["Linked", "Привязан", "Прив’язано"], notLinked: ["Not linked", "Не привязан", "Не прив’язано"], details: ["Details", "Подробности", "Подробиці"], notifications: ["Notifications", "Уведомления", "Сповіщення"],
  memberModules: ["Related settings", "Связанные настройки", "Пов’язані налаштування"], personalHint: ["Open a module to manage schedules and subscriptions.", "Откройте модуль для управления расписаниями и подписками.", "Відкрийте модуль для керування розкладами й підписками."],
  memberOnlyOwner: ["Only the family owner can edit member accounts and roles.", "Менять участников, аккаунты и роли может владелец семьи.", "Змінювати учасників, облікові записи та ролі може власник родини."],
  readOnly: ["This family is in read-only mode.", "Семья открыта в режиме только чтения.", "Родина відкрита в режимі лише читання."],
  quick: ["Quick actions", "Быстрые действия", "Швидкі дії"], attention: ["Needs attention", "Требует внимания", "Потребує уваги"], noIssues: ["No problems are currently reported.", "Сейчас проблем не сообщается.", "Зараз про проблеми не повідомляється."],
  enabled: ["Enabled", "Включено", "Увімкнено"], disabled: ["Disabled", "Выключено", "Вимкнено"], ready: ["Ready", "Готово", "Готово"], unknown: ["Not checked", "Не проверено", "Не перевірено"], unavailable: ["Unavailable", "Недоступно", "Недоступно"], configured: ["Configured", "Настроено", "Налаштовано"],
  checked: ["Last observation", "Последнее наблюдение", "Останнє спостереження"], readiness: ["Readiness", "Готовность", "Готовність"],
  localReady: ["Local workflows do not require Telegram or a language model.", "Локальным сценариям не нужны Telegram или языковая модель.", "Локальним сценаріям не потрібні Telegram чи мовна модель."],
  enabledHint: ["Disabling preserves records and settings.", "Выключение сохраняет записи и настройки.", "Вимкнення зберігає записи й налаштування."],
  settings: ["Settings", "Настройки", "Налаштування"], dailyUse: ["Open workspace", "Открыть рабочий раздел", "Відкрити робочий розділ"], health: ["System status", "Состояние системы", "Стан системи"],
  wizard: ["Setup guide", "Мастер настройки", "Майстер налаштування"], resume: ["Resume setup", "Продолжить настройку", "Продовжити налаштування"], welcome: ["Let's set up your family", "Настроим вашу семью", "Налаштуймо вашу родину"],
  wizardHint: ["Save each step when ready. You can return later; optional connections can wait.", "Сохраняйте шаги по мере готовности. Можно вернуться позже; необязательные подключения подождут.", "Зберігайте кроки за готовністю. Можна повернутися пізніше; необов’язкові підключення зачекають."],
  continue: ["Continue", "Продолжить", "Продовжити"], later: ["Set up later", "Настроить позже", "Налаштувати пізніше"], finish: ["Finish and open overview", "Завершить и открыть обзор", "Завершити й відкрити огляд"], review: ["Review your setup", "Проверка настройки", "Перевірка налаштування"],
  familyPack: ["Family tasks", "Семейные дела", "Родинні справи"], rewardPack: ["Motivation", "Мотивация", "Мотивація"], homePack: ["Home helper", "Домашний помощник", "Домашній помічник"],
  packHint: ["Packs add capabilities. Existing rules stay in place; penalties and device actions are configured separately.", "Наборы добавляют возможности. Текущие правила сохраняются; штрафы и действия с устройствами настраиваются отдельно.", "Набори додають можливості. Поточні правила зберігаються; штрафи й дії з пристроями налаштовуються окремо."],
  telegram: ["Telegram", "Telegram", "Telegram"], send: ["Message sending", "Отправка сообщений", "Надсилання повідомлень"], commands: ["Command reception", "Приём команд", "Приймання команд"], text: ["Ordinary text reception", "Приём обычного текста", "Приймання звичайного тексту"], group: ["Family group", "Семейная группа", "Родинна група"],
  invite: ["Create invitation", "Создать приглашение", "Створити запрошення"], inviteHint: ["Open this one-time invitation in the member's private bot chat, then return here to review and confirm the account.", "Откройте одноразовое приглашение в личном чате участника с ботом, затем вернитесь сюда для проверки и подтверждения аккаунта.", "Відкрийте одноразове запрошення в особистому чаті учасника з ботом, потім поверніться сюди для перевірки й підтвердження облікового запису."],
  expires: ["Expires", "Действует до", "Діє до"], copy: ["Copy", "Скопировать", "Скопіювати"], copied: ["Copied", "Скопировано", "Скопійовано"], close: ["Close", "Закрыть", "Закрити"],
  connectionHint: ["Connections and secret replacement use the integration's existing setup forms.", "Подключения и замена секретов доступны в существующих формах настройки интеграции.", "Підключення й заміна секретів доступні в наявних формах налаштування інтеграції."],
  integration: ["Open integration settings", "Открыть настройки интеграции", "Відкрити налаштування інтеграції"], configureTelegram: ["Configure Telegram", "Настроить Telegram", "Налаштувати Telegram"], configureAssistant: ["Configure language assistant", "Настроить понимание сообщений", "Налаштувати розуміння повідомлень"],
  recognition: ["Recognition preview", "Проверка распознавания", "Перевірка розпізнавання"], phrase: ["Enter a phrase", "Введите фразу", "Введіть фразу"], preview: ["Preview without executing", "Проверить без выполнения", "Перевірити без виконання"], previewHint: ["This preview does not create records, send messages or operate devices.", "Проверка не создаёт записи, не отправляет сообщения и не управляет устройствами.", "Перевірка не створює записи, не надсилає повідомлення й не керує пристроями."],
  action: ["Proposed action", "Предлагаемое действие", "Запропонована дія"], noMatch: ["No supported action recognized", "Поддерживаемое действие не распознано", "Підтримуваної дії не розпізнано"],
  schoolReminders: ["Preparation reminders", "Напоминания о подготовке", "Нагадування про підготовку"], reminderDay: ["When to remind", "Когда напоминать", "Коли нагадувати"], sameDay: ["On the day", "В день события", "У день події"], previousDay: ["The day before", "Накануне", "Напередодні"], time: ["Time", "Время", "Час"],
  autoPenalties: ["Automatic penalties", "Автоматические штрафы", "Автоматичні штрафи"], penaltyCap: ["Maximum automatic penalty points per day", "Максимум автоматических штрафных баллов в день", "Максимум автоматичних штрафних балів на день"],
  expiryReminders: ["Expiry reminders", "Напоминания о сроках годности", "Нагадування про строки придатності"], expiryDays: ["Warn this many days before expiry", "Предупреждать за столько дней до срока", "Попереджати за стільки днів до строку"],
  instructions: ["Delivery depends on the subscriptions and linked channel shown in the workspace.", "Доставка зависит от подписок и связанного канала, показанных в рабочем разделе.", "Доставка залежить від підписок і пов’язаного каналу, показаних у робочому розділі."],
  birthday: ["Date of birth (optional)", "Дата рождения (необязательно)", "Дата народження (необов’язково)"], avatar: ["Avatar", "Аватар", "Аватар"],
  zeroCap: ["0 prevents automatic penalty points. Manual awards are unchanged.", "0 запрещает автоматические штрафные баллы. Ручные оценки не меняются.", "0 забороняє автоматичні штрафні бали. Ручні оцінки не змінюються."],
  observed: ["Observed", "Наблюдалось", "Спостерігалося"],
  reason_not_configured: ["Configuration is incomplete", "Настройка не завершена", "Налаштування не завершено"],
  reason_provider_unavailable: ["Language provider is unavailable", "Языковой провайдер недоступен", "Мовний провайдер недоступний"],
  reason_network_not_configured: ["Network connection is not configured", "Сетевое подключение не настроено", "Мережеве підключення не налаштовано"],
  mobile_overview:["Home","Обзор","Огляд"], mobile_members:["Family","Семья","Родина"], mobile_modules:["Features","Функции","Функції"], mobile_connections:["Connect","Связь","Зв’язок"], mobile_advanced:["More","Ещё","Ще"],
  groupInvite:["Link family group","Связать семейную группу","Пов’язати родинну групу"],
  groupInviteHint:["Add your bot to the selected group and send this command there. Then refresh and confirm the group shown below.","Добавьте бота в нужную группу и отправьте в ней эту команду. Затем обновите статус и подтвердите показанную группу.","Додайте бота до потрібної групи й надішліть у ній цю команду. Потім оновіть стан і підтвердьте показану групу."],
  enrollment_issued:["Waiting for Telegram","Ожидаем действие в Telegram","Очікуємо дію в Telegram"],
  enrollment_captured:["Account found — owner confirmation required","Аккаунт найден — нужно подтверждение владельца","Обліковий запис знайдено — потрібне підтвердження власника"],
  enrollment_confirmed:["Link confirmed","Привязка подтверждена","Зв’язок підтверджено"],
  enrollment_expired:["Invitation expired. Create a new one.","Приглашение истекло. Создайте новое.","Запрошення прострочено. Створіть нове."],
  enrollment_superseded:["Replaced by a newer invitation","Заменено новым приглашением","Замінено новим запрошенням"],
  enrollmentConsent:["I checked that this Telegram account or group belongs to the selected member or family.","Я проверил(а), что этот аккаунт или группа Telegram соответствуют выбранному участнику или семье.","Я перевірив(ла), що цей обліковий запис або група Telegram відповідають вибраному учаснику чи родині."],
  confirmLink:["Confirm this link","Подтвердить привязку","Підтвердити зв’язок"],
  pendingInvites:["Pending invitations","Ожидающие приглашения","Запрошення, що очікують"],
  telegramChatId:["Telegram chat ID","ID чата Telegram","ID чату Telegram"], telegramUserId:["Telegram user ID","ID пользователя Telegram","ID користувача Telegram"],
  memberContext:["Settings for","Настройки для","Налаштування для"],
  memberContextHint:["Only this person's records and actions are shown.","Показаны записи и действия только этого участника.","Показано записи й дії лише цього учасника."],
  memberContextUnavailable:["This member is no longer active or is unavailable to your account. Return to the family overview.","Этот участник больше не активен или недоступен вашему аккаунту. Вернитесь к обзору семьи.","Цей учасник більше не активний або недоступний вашому обліковому запису. Поверніться до огляду родини."],
  schoolMemberContext:["Timetables, homework and reminders concern this child. Reminder subscriptions belong to the signed-in recipient shown below.","Расписания, задания и напоминания относятся к этому ребёнку. Подписки на напоминания принадлежат вошедшему получателю, указанному ниже.","Розклади, завдання й нагадування стосуються цієї дитини. Підписки на нагадування належать одержувачу, що увійшов і вказаний нижче."],
  digestSelfOnly:["Personal digests can be viewed and changed only by their recipient. Ask this member to sign in to their linked Home Assistant account; their preferences cannot be edited through your account.","Личные дайджесты может просматривать и менять только их получатель. Участнику нужно войти в связанную учётную запись Home Assistant; через ваш аккаунт его подписки не меняются.","Особисті дайджести може переглядати й змінювати лише їхній одержувач. Учаснику потрібно ввійти в пов’язаний обліковий запис Home Assistant; через ваш обліковий запис його підписки не змінюються."],
  allMembers:["All members","Все участники","Усі учасники"],
  reason_alarm_no_schedule:["No wake-up schedule","Нет расписания подъёма","Немає розкладу підйому"],
  reason_alarm_schedules_disabled:["Wake-up schedules are disabled","Расписания подъёма выключены","Розклади підйому вимкнено"],
  reason_alarm_output_missing:["Strict wake-up has no configured siren","Для строгого подъёма не настроена сирена","Для суворого підйому не налаштовано сирену"],
  reason_school_no_timetable:["No active school timetable","Нет действующего школьного расписания","Немає чинного шкільного розкладу"],
  reason_network_unavailable:["Network connection is unavailable","Сетевое подключение недоступно","Мережеве підключення недоступне"],
  reviewInvite:["Review invitation","Проверить приглашение","Перевірити запрошення"],
  inviteResumed:["This saved invitation can be reviewed here. If its link was lost, create a new invitation.","Здесь можно проверить сохранённое приглашение. Если ссылка потеряна, создайте новое.","Тут можна перевірити збережене запрошення. Якщо посилання втрачено, створіть нове."],
};
export const PANEL_COPY = Object.freeze(Object.fromEntries(
  ["en", "ru", "uk"].map((lang, i) => [lang, Object.freeze(
    Object.fromEntries(Object.entries(rows).map(([key, values]) => [key, values[i]]))
  )])
));
export const PANEL_LANGUAGES = Object.freeze({en:"English", ru:"Русский", uk:"Українська"});
export const PANEL_MODULES = Object.freeze([
  ["tasks", "📋", ["Tasks and reminders", "Задачи и напоминания", "Завдання й нагадування"], ["Assignments, recurring duties and reports", "Поручения, дежурства и отчёты", "Доручення, чергування й звіти"]],
  ["court", "⚖️", ["Points and rules", "Баллы и правила", "Бали й правила"], ["Rewards, limits and weekly review", "Поощрения, лимиты и итоги недели", "Заохочення, ліміти й підсумки тижня"]],
  ["school", "🎒", ["School", "Школа", "Школа"], ["Timetables, homework and preparation", "Расписания, домашние задания и подготовка", "Розклади, домашні завдання й підготовка"]],
  ["shopping", "🛒", ["Shopping", "Покупки", "Покупки"], ["Your shared shopping list", "Общий список покупок", "Спільний список покупок"]],
  ["pantry", "🥕", ["Food and pantry", "Продукты и запасы", "Продукти й запаси"], ["Stock, expiry dates and meal planning", "Запасы, сроки годности и меню", "Запаси, строки придатності й меню"]],
  ["maintenance", "🔧", ["Home maintenance", "Обслуживание дома", "Обслуговування дому"], ["Repairs, equipment and recurring maintenance", "Ремонт, оборудование и плановые работы", "Ремонт, обладнання й планові роботи"]],
  ["polls", "📊", ["Family polls", "Семейные голосования", "Родинні голосування"], ["Questions and shared decisions", "Опросы и общие решения", "Опитування й спільні рішення"]],
  ["presence", "🏠", ["Family presence", "Присутствие семьи", "Присутність родини"], ["Presence and arrival notifications", "Присутствие и уведомления о возвращении", "Присутність і сповіщення про повернення"]],
  ["digests", "📨", ["Personal digests", "Личные дайджесты", "Особисті дайджести"], ["Private summaries and subscriptions", "Личные сводки и подписки", "Особисті підсумки й підписки"]],
  ["alarms", "⏰", ["Wake-up alarms", "Будильники", "Будильники"], ["Schedules and wake-up confirmation", "Расписания и подтверждение подъёма", "Розклади й підтвердження підйому"]],
  ["routines", "🌤️", ["Routines", "Семейные рутины", "Родинні рутини"], ["Step-by-step family routines", "Пошаговые семейные сценарии", "Покрокові родинні сценарії"]],
  ["calendar", "📅", ["Calendar", "Календарь", "Календар"], ["Events and family logistics", "События и семейная логистика", "Події й родинна логістика"]],
  ["conversation", "💬", ["Language assistant", "Понимание сообщений", "Розуміння повідомлень"], ["Commands, language model and search", "Команды, языковая модель и поиск", "Команди, мовна модель й пошук"]],
  ["mikrotik", "🌐", ["Family network", "Семейная сеть", "Родинна мережа"], ["Devices and parental controls", "Устройства и родительский контроль", "Пристрої й батьківський контроль"]],
  ["price_watch", "🏷️", ["Price history", "История цен", "Історія цін"], ["Observed prices in shopping records", "Наблюдаемые цены в покупках", "Спостережувані ціни в покупках"]],
]);
export function moduleCopy(id, lang = "en") {
  const row = PANEL_MODULES.find(item => item[0] === id);
  const index = Math.max(0, ["en", "ru", "uk"].indexOf(lang));
  return row ? {id, icon:row[1], title:row[2][index], description:row[3][index]} : {id, icon:"⚙️", title:id, description:""};
}
