/* Local pantry copy for Family Assistant card. */

export const PANTRY_COPY = {
  en: {
    title: "Pantry",
    items: "Pantry items",
    archived: "Archived items",
    suggestions: "Shopping suggestions",
    new_item: "Add pantry item",
    edit: "Edit item",
    stock_set: "Set stock",
    archive: "Archive item",
    accept: "Add to shopping list",
    dismiss: "Dismiss suggestion",
    save: "Save",
    cancel: "Cancel",
    retry: "Retry",
    name: "Item name",
    quantity: "Current quantity",
    unit: "Unit of measurement",
    minimum_quantity: "Minimum stock level",
    expires_on: "Expiry date",
    category: "Category",
    location: "Storage location",
    note: "Parent note",
    reason: "Reason for change",
    empty: "No active pantry items.",
    no_suggestions: "No pending shopping suggestions.",
    low_stock: "Low stock",
    expiry_none: "No expiry date set",
    expiry_unknown: "Cannot assess expiry without the current date",
    expiry_expired: "Expired",
    expiry_today: "Expires today",
    expiry_expiring: "Expiring soon",
    expiry_fresh: "Recorded expiry is later",
    status_open: "Needs parent approval",
    status_accepted: "Added to shopping list",
    status_dismissed: "Dismissed",
    status_covered: "Already on shopping list",
    status_superseded: "Superseded by updated stock",
    error_invalid:
      "Check entered values. Stock must be non-negative with up to 3 decimal places.",
    error_stale: "Pantry data changed. Refresh and try again.",
    module_off: "Pantry module is disabled.",
    denied: "Parent access required for this action.",
    shopping_disabled:
      "Shopping module is disabled. Suggestions cannot be added to the shopping list.",
    inventory_hint:
      "Track household supplies, groceries, and staples in one shared place.",
    suggestion_hint:
      "Suggestions require parent approval. Approved items are only added to the shopping list, never ordered automatically.",
    expiry_hint:
      "One expiry date per record. Expiry does not deduct inventory; stock is factual and manually recorded.",
    stock_hint:
      "Stock quantities are factual, manual, and not inferred from expiry. Values allow up to 3 decimal places and must be non-negative (>= 0). Unit changes are relabeling only, not conversion, and require an explicit reason.",
    private_note_hint:
      "Pantry notes are private to parents and are never copied into the family shopping list.",
    expiry_reminders_title: "Expiry reminders",
    expiry_reminders_on: "Enabled.",
    expiry_reminders_off: "Disabled.",
    expiry_reminders_window:
      "After 09:00 in {timezone}, parents are notified privately when a recorded expiry is today or within the next {days} days. At most one reminder is created for each item revision.",
    expiry_reminders_window_zero:
      "After 09:00 in {timezone}, parents are notified privately only on the recorded expiry date. At most one reminder is created for each item revision.",
    expiry_reminders_factual:
      "A reminder does not deduct stock or determine whether food is safe.",
    expiry_reminders_settings:
      "The household owner can change this policy in the integration's Settings.",
    show_history: "Show history",
    history: "Item history",
    date_unknown: "Date unknown",
  },
  ru: {
    title: "Кладовая",
    items: "Запасы кладовой",
    archived: "Архив запасов",
    suggestions: "Предложения для покупок",
    new_item: "Добавить позицию",
    edit: "Редактировать позицию",
    stock_set: "Изменить остаток",
    archive: "В архив",
    accept: "Добавить в список покупок",
    dismiss: "Отклонить предложение",
    save: "Сохранить",
    cancel: "Отмена",
    retry: "Повторить",
    name: "Название позиции",
    quantity: "Текущее количество",
    unit: "Единица измерения",
    minimum_quantity: "Минимальный остаток",
    expires_on: "Срок годности",
    category: "Категория",
    location: "Место хранения",
    note: "Заметка для родителей",
    reason: "Причина изменения",
    empty: "В кладовой пока нет позиций.",
    no_suggestions: "Нет ожидающих предложений для покупок.",
    low_stock: "Запас заканчивается",
    expiry_none: "Срок годности не указан",
    expiry_unknown: "Нужна текущая дата для оценки срока",
    expiry_expired: "Истёк",
    expiry_today: "Истекает сегодня",
    expiry_expiring: "Скоро истекает",
    expiry_fresh: "Указанный срок наступит позже",
    status_open: "Требует подтверждения родителя",
    status_accepted: "Добавлено в список покупок",
    status_dismissed: "Отклонено",
    status_covered: "Уже в списке покупок",
    status_superseded: "Заменено обновлённым остатком",
    error_invalid:
      "Проверьте введённые данные. Количество должно быть неотрицательным и содержать не более 3 знаков после запятой.",
    error_stale:
      "Данные кладовой изменились. Обновите страницу и повторите попытку.",
    module_off: "Модуль кладовой отключён.",
    denied: "Для этого действия требуются права родителя.",
    shopping_disabled:
      "Модуль покупок выключен. Предложения нельзя добавить в список покупок.",
    inventory_hint:
      "Учёт бытовых припасов, продуктов и запасов в одном общем месте.",
    suggestion_hint:
      "Предложения требуют одобрения родителей. Одобренные пункты только добавляются в список покупок, заказы не оформляются.",
    expiry_hint:
      "Одна дата срока годности на запись. Срок годности не списывает запасы автоматически; остатки фактические и вносятся вручную.",
    stock_hint:
      "Остатки фактические, фиксируются вручную и не рассчитываются по сроку годности. Допускается до 3 знаков после запятой, количество должно быть не меньше нуля (>= 0). Смена единицы — это переименование ярлыка, а не пересчёт, и требует указания причины.",
    private_note_hint:
      "Заметки в кладовой видны только родителям и никогда не копируются в общий список покупок семьи.",
    expiry_reminders_title: "Напоминания о сроке годности",
    expiry_reminders_on: "Включены.",
    expiry_reminders_off: "Отключены.",
    expiry_reminders_window:
      "После 09:00 по часовому поясу {timezone} родители получают личное уведомление, если указанная дата срока годности — сегодня или наступит в течение следующих {days} суток. Для каждой редакции позиции напоминание создаётся один раз.",
    expiry_reminders_window_zero:
      "После 09:00 по часовому поясу {timezone} родители получают личное уведомление только в указанную дату срока годности. Для каждой редакции позиции напоминание создаётся один раз.",
    expiry_reminders_factual:
      "Напоминание не списывает остатки и не определяет, безопасен ли продукт.",
    expiry_reminders_settings:
      "Владелец пространства может изменить эту политику в настройках интеграции.",
    show_history: "Показать историю",
    history: "История изменений",
    date_unknown: "Дата неизвестна",
  },
  uk: {
    title: "Комора",
    items: "Запаси в коморі",
    archived: "Архів запасів",
    suggestions: "Пропозиції для покупок",
    new_item: "Додати позицію",
    edit: "Редагувати позицію",
    stock_set: "Змінити залишок",
    archive: "В архів",
    accept: "Додати до списку покупок",
    dismiss: "Відхилити пропозицію",
    save: "Зберегти",
    cancel: "Скасувати",
    retry: "Повторити",
    name: "Назва позиції",
    quantity: "Поточна кількість",
    unit: "Одиниця вимірювання",
    minimum_quantity: "Мінімальний залишок",
    expires_on: "Термін придатності",
    category: "Категорія",
    location: "Місце зберігання",
    note: "Примітка для батьків",
    reason: "Причина зміни",
    empty: "У коморі поки немає активних позицій.",
    no_suggestions: "Немає пропозицій для покупок, які очікують розгляду.",
    low_stock: "Закінчується",
    expiry_none: "Термін придатності не зазначено",
    expiry_unknown: "Потрібна поточна дата для оцінки строку",
    expiry_expired: "Термін минув",
    expiry_today: "Спливає сьогодні",
    expiry_expiring: "Спливає незабаром",
    expiry_fresh: "Зазначений строк настане пізніше",
    status_open: "Потребує схвалення батьків",
    status_accepted: "Додано до списку покупок",
    status_dismissed: "Відхилено",
    status_covered: "Вже є у списку покупок",
    status_superseded: "Замінено оновленим залишком",
    error_invalid:
      "Перевірте введені значення. Кількість має бути невід'ємною і містити не більше 3 знаків після коми.",
    error_stale: "Дані комори змінилися. Оновіть сторінку та повторіть спробу.",
    module_off: "Модуль комори вимкнено.",
    denied: "Для цієї дії потрібні права батьків.",
    shopping_disabled:
      "Модуль покупок вимкнено. Пропозиції неможливо додати до списку покупок.",
    inventory_hint:
      "Облік побутових припасів, продуктів і витратних матеріалів в одному місці.",
    suggestion_hint:
      "Пропозиції потребують схвалення батьків. Схвалені позиції лише додаються до списку покупок, замовлення автоматично не створюються.",
    expiry_hint:
      "Один термін придатності на запис. Термін придатності не списує запаси автоматично; залишки є фактичними та фіксуються вручну.",
    stock_hint:
      "Залишки фактичні, вносяться вручну і не вираховуються за терміном придатності. Дозволено до 3 знаків після коми, кількість має бути не меншою за нуль (>= 0). Зміна одиниці є лише перейменуванням позначки, а не автоматичним перерахунком, і вимагає зазначення причини.",
    private_note_hint:
      "Примітки в коморі доступні лише батькам і ніколи не копіюються до спільного сімейного списку покупок.",
    expiry_reminders_title: "Нагадування про термін придатності",
    expiry_reminders_on: "Увімкнено.",
    expiry_reminders_off: "Вимкнено.",
    expiry_reminders_window:
      "Після 09:00 за часовим поясом {timezone} батьки отримують приватне сповіщення, якщо зазначена дата терміну придатності — сьогодні або настане протягом наступних {days} діб. Для кожної редакції позиції нагадування створюється один раз.",
    expiry_reminders_window_zero:
      "Після 09:00 за часовим поясом {timezone} батьки отримують приватне сповіщення лише в зазначену дату терміну придатності. Для кожної редакції позиції нагадування створюється один раз.",
    expiry_reminders_factual:
      "Нагадування не списує залишки й не визначає, чи є продукт безпечним.",
    expiry_reminders_settings:
      "Власник простору може змінити цю політику в налаштуваннях інтеграції.",
    show_history: "Показати історію",
    history: "Історія змін",
    date_unknown: "Дата невідома",
  },
};
