/* Localized copy for private-mapping family polls. */

export const POLLS_COPY = {
  en: {
    title: "Family polls",
    help: "Ask a defined group of current family members and close the poll before showing totals.",
    privacy_warning:
      "Votes are stored by member so each eligible person can change their vote. The ballot mapping is hidden here, but this is not anonymous; totals in a small group can reveal choices.",
    no_automatic_effects:
      "A poll records opinions only. It does not start routines, change tasks, award points, or control devices.",
    open_polls: "Open polls",
    closed_polls: "Closed results",
    archived_polls: "Archived polls",
    no_open: "No open polls.",
    no_closed: "No closed polls.",
    no_archived: "No archived polls.",
    create: "Create poll",
    question: "Question",
    options: "Choices",
    option: "Choice",
    add_option: "Add choice",
    remove_option: "Remove choice",
    eligible: "Eligible family members",
    closes_at: "Closes",
    timezone: "Household time zone",
    dst_gap: "That local time does not exist because of a clock change.",
    dst_ambiguous:
      "That local time occurs twice. Choose which occurrence you mean.",
    dst_choice: "Clock-change occurrence",
    dst_choose: "Choose an occurrence",
    dst_first: "First occurrence",
    dst_second: "Second occurrence",
    review_create: "Review exact new poll",
    confirm_create:
      "I checked the question, every choice, eligible members, deadline, and privacy warning",
    vote: "Vote",
    revote: "Change vote",
    review_vote: "Review exact vote",
    confirm_vote:
      "I checked this exact choice and understand it replaces my previous vote",
    close: "Close poll",
    review_close: "Review closing this poll",
    confirm_close:
      "I checked the named poll and want to close voting and publish aggregate totals",
    archive: "Archive poll",
    review_archive: "Review archiving this poll",
    confirm_archive: "I checked the named closed poll and want to archive it",
    purge: "Permanently delete poll",
    review_purge: "Review permanent poll deletion",
    purge_warning:
      "Permanent deletion removes this archived poll and its aggregate result. This cannot be undone from the card.",
    confirm_purge:
      "I checked the named archived poll and want to permanently delete it",
    save: "Save reviewed request",
    retry: "Retry exact request",
    retry_hint:
      "The result is unconfirmed. Retry sends the same reviewed request and operation ID.",
    cancel: "Cancel",
    eligible_count: "Eligible",
    cast_count: "Votes cast",
    results: "Aggregate results",
    your_vote: "Your current vote",
    no_vote: "Not voted",
    created_by: "Created by",
    revision: "version",
    status_open: "Open",
    status_closed: "Closed",
    status_archived: "Archived",
    results_hidden: "Totals appear only after the poll closes.",
    unavailable_member: "Unavailable family member",
    invalid:
      "Check the question, unique choices, eligible members, deadline, and required confirmation.",
    stale:
      "The poll, family access, or configuration changed. Start again from current data.",
  },
  ru: {
    title: "Семейные голосования",
    help: "Задайте вопрос выбранным участникам семьи; итоги появятся только после закрытия голосования.",
    privacy_warning:
      "Голос хранится с участником, чтобы он мог изменить выбор. Связка голосов с участниками здесь скрыта, но голосование не анонимное; в маленькой группе выбор можно угадать по итогам.",
    no_automatic_effects:
      "Голосование только фиксирует мнения. Оно не запускает рутины, не меняет задачи, баллы или устройства.",
    open_polls: "Открытые голосования",
    closed_polls: "Закрытые итоги",
    archived_polls: "Архив голосований",
    no_open: "Открытых голосований нет.",
    no_closed: "Закрытых голосований нет.",
    no_archived: "Архив пуст.",
    create: "Создать голосование",
    question: "Вопрос",
    options: "Варианты ответа",
    option: "Вариант",
    add_option: "Добавить вариант",
    remove_option: "Удалить вариант",
    eligible: "Кто может голосовать",
    closes_at: "Закрывается",
    timezone: "Часовой пояс семьи",
    dst_gap: "Такого местного времени нет из-за перевода часов.",
    dst_ambiguous:
      "Это местное время встречается дважды. Выберите нужный момент.",
    dst_choice: "Момент при переводе часов",
    dst_choose: "Выберите момент",
    dst_first: "Первый момент",
    dst_second: "Второй момент",
    review_create: "Проверить точное новое голосование",
    confirm_create:
      "Я проверил(а) вопрос, все варианты, участников, срок и предупреждение о приватности",
    vote: "Проголосовать",
    revote: "Изменить голос",
    review_vote: "Проверить точный голос",
    confirm_vote:
      "Я проверил(а) этот вариант и понимаю, что он заменит мой предыдущий голос",
    close: "Закрыть голосование",
    review_close: "Проверить закрытие голосования",
    confirm_close:
      "Я проверил(а) указанное голосование и хочу закрыть приём голосов и показать общие итоги",
    archive: "Перенести в архив",
    review_archive: "Проверить перенос в архив",
    confirm_archive:
      "Я проверил(а) указанное закрытое голосование и хочу перенести его в архив",
    purge: "Удалить голосование навсегда",
    review_purge: "Проверить окончательное удаление",
    purge_warning:
      "Окончательное удаление уберёт архивное голосование и общие итоги. В карточке это нельзя отменить.",
    confirm_purge:
      "Я проверил(а) указанное архивное голосование и хочу удалить его навсегда",
    save: "Сохранить проверенный запрос",
    retry: "Повторить точный запрос",
    retry_hint:
      "Результат не подтверждён. Повтор отправит тот же проверенный запрос с тем же идентификатором операции.",
    cancel: "Отмена",
    eligible_count: "Могут голосовать",
    cast_count: "Подано голосов",
    results: "Общие итоги",
    your_vote: "Ваш текущий голос",
    no_vote: "Голос не подан",
    created_by: "Создал(а)",
    revision: "версия",
    status_open: "Открыто",
    status_closed: "Закрыто",
    status_archived: "В архиве",
    results_hidden: "Итоги появятся только после закрытия голосования.",
    unavailable_member: "Недоступный участник семьи",
    invalid:
      "Проверьте вопрос, уникальные варианты, участников, срок и обязательное подтверждение.",
    stale:
      "Голосование, семейный доступ или настройки изменились. Начните заново с актуальных данных.",
  },
  uk: {
    title: "Родинні голосування",
    help: "Поставте запитання вибраним членам родини; підсумки з’являться лише після закриття голосування.",
    privacy_warning:
      "Голос зберігається разом з учасником, щоб він міг змінити вибір. Зв’язок голосів з учасниками тут приховано, але голосування не анонімне; у малій групі вибір можна вгадати за підсумками.",
    no_automatic_effects:
      "Голосування лише фіксує думки. Воно не запускає рутини, не змінює завдання, бали чи пристрої.",
    open_polls: "Відкриті голосування",
    closed_polls: "Закриті підсумки",
    archived_polls: "Архів голосувань",
    no_open: "Відкритих голосувань немає.",
    no_closed: "Закритих голосувань немає.",
    no_archived: "Архів порожній.",
    create: "Створити голосування",
    question: "Запитання",
    options: "Варіанти відповіді",
    option: "Варіант",
    add_option: "Додати варіант",
    remove_option: "Видалити варіант",
    eligible: "Хто може голосувати",
    closes_at: "Закривається",
    timezone: "Часовий пояс родини",
    dst_gap: "Такого місцевого часу немає через переведення годинника.",
    dst_ambiguous:
      "Цей місцевий час трапляється двічі. Виберіть потрібний момент.",
    dst_choice: "Момент під час переведення годинника",
    dst_choose: "Виберіть момент",
    dst_first: "Перший момент",
    dst_second: "Другий момент",
    review_create: "Перевірити точне нове голосування",
    confirm_create:
      "Я перевірив(ла) запитання, усі варіанти, учасників, строк і попередження про приватність",
    vote: "Проголосувати",
    revote: "Змінити голос",
    review_vote: "Перевірити точний голос",
    confirm_vote:
      "Я перевірив(ла) цей варіант і розумію, що він замінить мій попередній голос",
    close: "Закрити голосування",
    review_close: "Перевірити закриття голосування",
    confirm_close:
      "Я перевірив(ла) вказане голосування і хочу закрити приймання голосів та показати загальні підсумки",
    archive: "Перенести до архіву",
    review_archive: "Перевірити перенесення до архіву",
    confirm_archive:
      "Я перевірив(ла) вказане закрите голосування і хочу перенести його до архіву",
    purge: "Видалити голосування назавжди",
    review_purge: "Перевірити остаточне видалення",
    purge_warning:
      "Остаточне видалення прибере архівне голосування та загальні підсумки. У картці це не можна скасувати.",
    confirm_purge:
      "Я перевірив(ла) вказане архівне голосування і хочу видалити його назавжди",
    save: "Зберегти перевірений запит",
    retry: "Повторити точний запит",
    retry_hint:
      "Результат не підтверджено. Повтор надішле той самий перевірений запит із тим самим ідентифікатором операції.",
    cancel: "Скасувати",
    eligible_count: "Можуть голосувати",
    cast_count: "Подано голосів",
    results: "Загальні підсумки",
    your_vote: "Ваш поточний голос",
    no_vote: "Голос не подано",
    created_by: "Створив(ла)",
    revision: "версія",
    status_open: "Відкрите",
    status_closed: "Закрите",
    status_archived: "В архіві",
    results_hidden: "Підсумки з’являться лише після закриття голосування.",
    unavailable_member: "Недоступний член родини",
    invalid:
      "Перевірте запитання, унікальні варіанти, учасників, строк і обов’язкове підтвердження.",
    stale:
      "Голосування, родинний доступ або налаштування змінилися. Почніть знову з актуальних даних.",
  },
};
