/* Localized copy for consent-bound, display-only presence evidence. */

export const PRESENCE_COPY = {
  en: {
    managed_children: "Children's sharing",
    guardian_review: "Review sharing for a child",
    guardian_help: "Owners and parents can explicitly enable or stop a child's reported home/away status. Adults consent only for themselves. Replacing the source, child identity or consenting parent invalidates guardian consent. This does not share coordinates or start devices.",
    consent_source: "Sharing choice",
    consent_self: "By the family member",
    consent_guardian: "By a parent",
    consent_none: "Not set",
    title: "Family presence",
    guide: "How reported presence works",
    help: "One source selected by the household owner reports home, away, or unknown. This is limited evidence, not precise location or confirmed occupancy.",
    sharing:
      "Enabling shares only the normalized status and observation time with current owners and parents.",
    no_effects:
      "Presence does not start routines, change tasks or points, send notifications, or control devices.",
    source_help:
      "A household owner configures sources in integration Settings. Sources remain unread until the member enables sharing, or a parent explicitly enables it for a child.",
    your_presence: "Your reported presence",
    shared_presence: "Presence shared with parents",
    no_shared: "No other family members currently share presence with you.",
    status: "Reported status",
    reported_home: "Reported home",
    reported_away: "Reported away",
    unknown: "Unknown",
    reason: "Evidence",
    fresh: "Fresh report",
    stale: "Report is stale",
    unavailable: "Source unavailable or unreadable",
    unconfigured: "No current source is configured",
    not_shared: "Not shared",
    observed: "Observed",
    preference: "Sharing with owners and parents",
    enabled: "Enabled",
    disabled: "Disabled",
    enable: "Enable sharing",
    disable: "Disable sharing",
    unavailable_action:
      "Configure a current source in integration Settings before enabling sharing.",
    review_title: "Review presence sharing",
    person: "Family member",
    choice: "Choice",
    share_choice: "Share normalized reported presence",
    stop_choice: "Stop sharing reported presence",
    member_version: "Member version",
    binding_version: "Source binding version",
    subscription_version: "Sharing version",
    absent: "not created",
    confirm:
      "I checked the named family member and understand that this shares reported home, away, or unknown—not precise location or confirmed occupancy.",
    save: "Save sharing choice",
    retry: "Retry exact request",
    cancel: "Cancel",
    unavailable_member: "Current family member",
  },
  ru: {
    managed_children: "Передача статуса детей",
    guardian_review: "Проверка передачи статуса ребёнка",
    guardian_help: "Владелец и родители могут явно включить или остановить передачу статуса ребёнка «дома/не дома». Взрослые дают согласие только за себя. Замена источника, учётной записи ребёнка или давшего согласие родителя отменяет родительское согласие. Координаты не передаются, устройства не запускаются.",
    consent_source: "Кто разрешил передачу",
    consent_self: "Сам участник",
    consent_guardian: "Родитель",
    consent_none: "Не настроено",
    title: "Присутствие семьи",
    guide: "Как работает статус присутствия",
    help: "Один источник, выбранный владельцем семьи, сообщает статус «дома», «не дома» или «неизвестно». Это ограниченные данные, а не точное местоположение или подтверждённое присутствие.",
    sharing:
      "При включении другим текущим владельцам и родителям передаются только нормализованный статус и время наблюдения.",
    no_effects:
      "Статус присутствия не запускает рутины, не меняет задачи или баллы, не отправляет уведомления и не управляет устройствами.",
    source_help:
      "Владелец настраивает источники в настройках интеграции. Источник не читается, пока участник сам не включит передачу статуса или родитель явно не включит её для ребёнка.",
    your_presence: "Ваш статус присутствия",
    shared_presence: "Статусы, которыми поделились с родителями",
    no_shared:
      "Сейчас другие участники семьи не делятся с вами статусом присутствия.",
    status: "Сообщённый статус",
    reported_home: "По данным источника — дома",
    reported_away: "По данным источника — не дома",
    unknown: "Неизвестно",
    reason: "Данные",
    fresh: "Свежее сообщение источника",
    stale: "Сообщение устарело",
    unavailable: "Источник недоступен или не читается",
    unconfigured: "Актуальный источник не настроен",
    not_shared: "Передача выключена",
    observed: "Время наблюдения",
    preference: "Передача владельцам и родителям",
    enabled: "Включена",
    disabled: "Выключена",
    enable: "Включить передачу",
    disable: "Выключить передачу",
    unavailable_action:
      "Чтобы включить передачу, сначала настройте актуальный источник в настройках интеграции.",
    review_title: "Проверка передачи статуса присутствия",
    person: "Участник семьи",
    choice: "Выбор",
    share_choice: "Передавать нормализованный статус присутствия",
    stop_choice: "Прекратить передачу статуса присутствия",
    member_version: "Версия участника",
    binding_version: "Версия привязки источника",
    subscription_version: "Версия настройки передачи",
    absent: "ещё не создана",
    confirm:
      "Я проверил(а) указанного участника и понимаю, что передаются статусы «дома», «не дома» или «неизвестно», а не точное местоположение или подтверждённое присутствие.",
    save: "Сохранить выбор",
    retry: "Повторить точный запрос",
    cancel: "Отмена",
    unavailable_member: "Текущий участник семьи",
  },
  uk: {
    managed_children: "Поширення статусу дітей",
    guardian_review: "Перевірка поширення статусу дитини",
    guardian_help: "Власник і батьки можуть явно ввімкнути або зупинити поширення статусу дитини «удома/не вдома». Дорослі дають згоду лише за себе. Заміна джерела, облікового запису дитини чи того з батьків, хто дав згоду, скасовує батьківську згоду. Координати не поширюються, пристрої не запускаються.",
    consent_source: "Хто дозволив поширення",
    consent_self: "Сам учасник",
    consent_guardian: "Хтось із батьків",
    consent_none: "Не налаштовано",
    title: "Присутність родини",
    guide: "Як працює статус присутності",
    help: "Одне джерело, вибране власником родини, повідомляє статус «удома», «не вдома» або «невідомо». Це обмежені дані, а не точне місцезнаходження чи підтверджена присутність.",
    sharing:
      "Після ввімкнення іншим чинним власникам і батькам передаються лише нормалізований статус і час спостереження.",
    no_effects:
      "Статус присутності не запускає рутини, не змінює завдання чи бали, не надсилає сповіщення та не керує пристроями.",
    source_help:
      "Власник налаштовує джерела в налаштуваннях інтеграції. Джерело не читається, доки учасник сам не ввімкне поширення статусу або хтось із батьків явно не ввімкне його для дитини.",
    your_presence: "Ваш статус присутності",
    shared_presence: "Статуси, якими поділилися з батьками",
    no_shared:
      "Зараз інші члени родини не діляться з вами статусом присутності.",
    status: "Повідомлений статус",
    reported_home: "За даними джерела — удома",
    reported_away: "За даними джерела — не вдома",
    unknown: "Невідомо",
    reason: "Дані",
    fresh: "Свіже повідомлення джерела",
    stale: "Повідомлення застаріло",
    unavailable: "Джерело недоступне або не читається",
    unconfigured: "Чинне джерело не налаштоване",
    not_shared: "Поширення вимкнене",
    observed: "Час спостереження",
    preference: "Поширення власникам і батькам",
    enabled: "Увімкнене",
    disabled: "Вимкнене",
    enable: "Увімкнути поширення",
    disable: "Вимкнути поширення",
    unavailable_action:
      "Щоб увімкнути поширення, спочатку налаштуйте чинне джерело в налаштуваннях інтеграції.",
    review_title: "Перевірка поширення статусу присутності",
    person: "Член родини",
    choice: "Вибір",
    share_choice: "Поширювати нормалізований статус присутності",
    stop_choice: "Припинити поширення статусу присутності",
    member_version: "Версія учасника",
    binding_version: "Версія прив’язки джерела",
    subscription_version: "Версія налаштування поширення",
    absent: "ще не створена",
    confirm:
      "Я перевірив(-ла) вказаного учасника й розумію, що поширюються статуси «удома», «не вдома» або «невідомо», а не точне місцезнаходження чи підтверджена присутність.",
    save: "Зберегти вибір",
    retry: "Повторити точний запит",
    cancel: "Скасувати",
    unavailable_member: "Поточний член родини",
  },
};
