/* Local copy for the optional, manually reviewed Mealie recipe flow. */

export const RECIPES_COPY = {
  en: {
    title: "Recipes from Mealie",
    help: "Mealie is an optional external recipe source. Imported text and amounts are suggestions: check every ingredient manually. Nothing here orders shopping, checks allergens, or makes a food-safety assessment.",
    query: "Recipe search",
    query_hint: "Leave blank and search to browse recipes.",
    search: "Search recipes",
    loading: "Loading recipes…",
    no_results: "No recipes found.",
    previous: "Previous page",
    next: "Next page",
    page: "Page",
    use_recipe: "Use this recipe",
    clear: "Clear recipe search",
    back: "Back",
    candidate: "Recipe candidate",
    source_servings: "Mealie servings suggestion",
    source_display: "Source line",
    week_start: "Week start (Monday)",
    date: "Meal date",
    slot: "Meal slot",
    plan_title: "Plan and meal title",
    servings: "Servings",
    servings_hint:
      "Changing servings never scales ingredient quantities. Enter every total manually.",
    ingredients: "Ingredients",
    name: "Ingredient name",
    unit: "Unit",
    quantity: "Total quantity",
    add_ingredient: "Add ingredient",
    remove_ingredient: "Remove ingredient",
    restore_ingredient: "Restore ingredient",
    removed: "Removed",
    verify_line: "I manually checked and corrected this source line",
    requires_check: "Manual correction required",
    review: "Review exact draft",
    review_title: "Review new meal-plan draft",
    review_hint:
      "This creates one new draft plan only. It does not update an existing plan or create shopping records.",
    confirm_exact:
      "I checked the date, meal, servings, and every ingredient above",
    create_draft: "Create this draft",
    retry: "Retry exact request",
    cancel: "Cancel",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snack",
    blocker_servings_required: "Enter servings from 1 to 50.",
    blocker_too_many_ingredients:
      "Remove ingredients explicitly until no more than 20 remain.",
    blocker_missing_name: "Ingredient name is missing.",
    blocker_missing_unit: "Unit is missing.",
    blocker_missing_quantity: "Quantity is missing.",
    blocker_invalid_quantity: "Quantity is invalid.",
    blocker_unsupported_reference:
      "This recipe reference cannot be followed; enter the ingredient manually or remove it.",
    blocker_manual_units: "Enter and verify the unit and quantity manually.",
    invalid:
      "Check the week, date, title, servings, and ingredients. Retained blocked lines need manual verification.",
    lookup_failed: "Could not load recipes from Mealie.",
    provider_bad_response: "Mealie returned an unsupported recipe response.",
    source_changed: "The recipe source changed. Search again.",
  },
  ru: {
    title: "Рецепты из Mealie",
    help: "Mealie — необязательный внешний источник рецептов. Импортированные тексты и количества служат подсказкой: проверяйте каждый ингредиент вручную. Здесь не оформляются покупки, не проверяются аллергены и не даётся оценка пищевой безопасности.",
    query: "Поиск рецепта",
    query_hint:
      "Оставьте поле пустым и запустите поиск, чтобы посмотреть рецепты.",
    search: "Найти рецепты",
    loading: "Загружаю рецепты…",
    no_results: "Рецепты не найдены.",
    previous: "Предыдущая страница",
    next: "Следующая страница",
    page: "Страница",
    use_recipe: "Использовать рецепт",
    clear: "Очистить поиск рецептов",
    back: "Назад",
    candidate: "Рецепт-кандидат",
    source_servings: "Подсказка Mealie о порциях",
    source_display: "Строка источника",
    week_start: "Начало недели (понедельник)",
    date: "Дата блюда",
    slot: "Приём пищи",
    plan_title: "Название плана и блюда",
    servings: "Порции",
    servings_hint:
      "Изменение числа порций никогда не пересчитывает ингредиенты. Укажите каждый итог вручную.",
    ingredients: "Ингредиенты",
    name: "Название ингредиента",
    unit: "Единица",
    quantity: "Общее количество",
    add_ingredient: "Добавить ингредиент",
    remove_ingredient: "Удалить ингредиент",
    restore_ingredient: "Вернуть ингредиент",
    removed: "Удалён",
    verify_line: "Я вручную проверил(а) и исправил(а) эту строку источника",
    requires_check: "Нужна ручная проверка",
    review: "Проверить точный черновик",
    review_title: "Проверка нового черновика меню",
    review_hint:
      "Будет создан только один новый черновик плана. Существующий план и список покупок не изменятся.",
    confirm_exact: "Я проверил(а) дату, блюдо, порции и каждый ингредиент выше",
    create_draft: "Создать этот черновик",
    retry: "Повторить тот же запрос",
    cancel: "Отмена",
    breakfast: "Завтрак",
    lunch: "Обед",
    dinner: "Ужин",
    snack: "Перекус",
    blocker_servings_required: "Укажите от 1 до 50 порций.",
    blocker_too_many_ingredients:
      "Удаляйте ингредиенты явно, пока не останется не более 20.",
    blocker_missing_name: "Не указано название ингредиента.",
    blocker_missing_unit: "Не указана единица.",
    blocker_missing_quantity: "Не указано количество.",
    blocker_invalid_quantity: "Количество указано неверно.",
    blocker_unsupported_reference:
      "Эту ссылку на рецепт нельзя открыть; внесите ингредиент вручную или удалите строку.",
    blocker_manual_units: "Введите и проверьте единицу и количество вручную.",
    invalid:
      "Проверьте неделю, дату, название, порции и ингредиенты. Для оставленных проблемных строк нужна ручная проверка.",
    lookup_failed: "Не удалось загрузить рецепты из Mealie.",
    provider_bad_response: "Mealie вернул неподдерживаемый ответ с рецептом.",
    source_changed: "Источник рецептов изменился. Выполните поиск заново.",
  },
  uk: {
    title: "Рецепти з Mealie",
    help: "Mealie — необов’язкове зовнішнє джерело рецептів. Імпортовані тексти й кількості є підказкою: перевіряйте кожен інгредієнт вручну. Тут не оформлюються покупки, не перевіряються алергени й не надається оцінка харчової безпеки.",
    query: "Пошук рецепта",
    query_hint:
      "Залиште поле порожнім і запустіть пошук, щоб переглянути рецепти.",
    search: "Знайти рецепти",
    loading: "Завантажую рецепти…",
    no_results: "Рецептів не знайдено.",
    previous: "Попередня сторінка",
    next: "Наступна сторінка",
    page: "Сторінка",
    use_recipe: "Використати рецепт",
    clear: "Очистити пошук рецептів",
    back: "Назад",
    candidate: "Рецепт-кандидат",
    source_servings: "Підказка Mealie щодо порцій",
    source_display: "Рядок джерела",
    week_start: "Початок тижня (понеділок)",
    date: "Дата страви",
    slot: "Прийом їжі",
    plan_title: "Назва плану та страви",
    servings: "Порції",
    servings_hint:
      "Зміна кількості порцій ніколи не перераховує інгредієнти. Укажіть кожен підсумок вручну.",
    ingredients: "Інгредієнти",
    name: "Назва інгредієнта",
    unit: "Одиниця",
    quantity: "Загальна кількість",
    add_ingredient: "Додати інгредієнт",
    remove_ingredient: "Видалити інгредієнт",
    restore_ingredient: "Повернути інгредієнт",
    removed: "Видалено",
    verify_line: "Я вручну перевірив(ла) й виправив(ла) цей рядок джерела",
    requires_check: "Потрібна ручна перевірка",
    review: "Перевірити точну чернетку",
    review_title: "Перевірка нової чернетки меню",
    review_hint:
      "Буде створено лише одну нову чернетку плану. Наявний план і список покупок не зміняться.",
    confirm_exact:
      "Я перевірив(ла) дату, страву, порції та кожен інгредієнт вище",
    create_draft: "Створити цю чернетку",
    retry: "Повторити той самий запит",
    cancel: "Скасувати",
    breakfast: "Сніданок",
    lunch: "Обід",
    dinner: "Вечеря",
    snack: "Перекус",
    blocker_servings_required: "Укажіть від 1 до 50 порцій.",
    blocker_too_many_ingredients:
      "Видаляйте інгредієнти явно, доки не залишиться щонайбільше 20.",
    blocker_missing_name: "Не вказано назву інгредієнта.",
    blocker_missing_unit: "Не вказано одиницю.",
    blocker_missing_quantity: "Не вказано кількість.",
    blocker_invalid_quantity: "Кількість указано неправильно.",
    blocker_unsupported_reference:
      "Це посилання на рецепт не можна відкрити; внесіть інгредієнт вручну або видаліть рядок.",
    blocker_manual_units: "Введіть і перевірте одиницю та кількість вручну.",
    invalid:
      "Перевірте тиждень, дату, назву, порції та інгредієнти. Для залишених проблемних рядків потрібна ручна перевірка.",
    lookup_failed: "Не вдалося завантажити рецепти з Mealie.",
    provider_bad_response:
      "Mealie повернув непідтримувану відповідь із рецептом.",
    source_changed: "Джерело рецептів змінилося. Виконайте пошук знову.",
  },
};
