/* Local copy for manually reviewed school timetables. */

export const SCHOOL_COPY = {
  en: {
    title: "School timetable",
    help: "Parents maintain weekly lesson times and materials. Children see only their own upcoming school agenda.",
    timezone: "Household time zone",
    upcoming: "Next 14 days",
    no_upcoming: "No upcoming lessons in this period.",
    timetables: "Timetables",
    no_timetables: "No timetables recorded.",
    new_timetable: "New timetable",
    edit: "Edit timetable",
    archive: "Archive timetable",
    member: "Child",
    timetable_title: "Timetable title",
    valid_from: "Valid from",
    valid_until: "Valid until (optional)",
    exceptions: "Dates without lessons",
    exceptions_hint:
      "One YYYY-MM-DD date per line, within the timetable period.",
    lessons: "Weekly lessons",
    add_lesson: "Add lesson",
    remove_lesson: "Remove lesson",
    weekday: "Weekday",
    start: "Start",
    end: "End",
    subject: "Subject",
    room: "Room (optional)",
    materials: "Materials",
    materials_hint: "One item per line; up to 12 for this lesson.",
    backpack_routine: "Backpack routine (optional)",
    backpack_none: "No linked routine",
    backpack_unavailable: "Unavailable pinned routine",
    backpack_unavailable_hint:
      "This saved routine version is no longer available. Explicitly choose no routine or a current replacement before reviewing.",
    revision: "version",
    backpack_hint:
      "This only links the current routine template version. It does not start or change a routine.",
    review: "Review exact timetable",
    review_title: "Review school timetable",
    confirm_save:
      "I checked the child, dates, every lesson, materials, and optional routine link",
    create: "Create timetable",
    save: "Save replacement",
    retry: "Retry exact request",
    cancel: "Cancel",
    archive_title: "Archive timetable?",
    reason: "Archive reason",
    confirm_archive: "I checked the timetable and want to archive it",
    history: "History",
    action_created: "Created",
    action_updated: "Updated",
    action_archived: "Archived",
    status_active: "Active",
    status_archived: "Archived",
    readonly: "Read-only",
    unknown_member: "Family member",
    none: "None",
    invalid:
      "Check the child, dates, lessons, overlaps, materials, and routine link.",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
  },
  ru: {
    title: "Школьное расписание",
    help: "Родители ведут еженедельное расписание уроков и материалов. Ребёнок видит только свою ближайшую школьную повестку.",
    timezone: "Часовой пояс семьи",
    upcoming: "Ближайшие 14 дней",
    no_upcoming: "В этом периоде нет предстоящих уроков.",
    timetables: "Расписания",
    no_timetables: "Расписаний пока нет.",
    new_timetable: "Новое расписание",
    edit: "Изменить расписание",
    archive: "Архивировать расписание",
    member: "Ребёнок",
    timetable_title: "Название расписания",
    valid_from: "Действует с",
    valid_until: "Действует до (необязательно)",
    exceptions: "Даты без уроков",
    exceptions_hint:
      "Одна дата ГГГГ-ММ-ДД на строку в пределах периода расписания.",
    lessons: "Уроки недели",
    add_lesson: "Добавить урок",
    remove_lesson: "Удалить урок",
    weekday: "День недели",
    start: "Начало",
    end: "Конец",
    subject: "Предмет",
    room: "Кабинет (необязательно)",
    materials: "Материалы",
    materials_hint: "Одна позиция на строку; до 12 для этого урока.",
    backpack_routine: "Рутина сборки рюкзака (необязательно)",
    backpack_none: "Без связанной рутины",
    backpack_unavailable: "Недоступная закреплённая рутина",
    backpack_unavailable_hint:
      "Эта сохранённая версия рутины больше недоступна. Перед проверкой явно выберите вариант без рутины или текущую замену.",
    revision: "версия",
    backpack_hint:
      "Выбирается только текущая версия шаблона. Это не запускает и не изменяет рутину.",
    review: "Проверить точное расписание",
    review_title: "Проверка школьного расписания",
    confirm_save:
      "Я проверил(а) ребёнка, даты, все уроки, материалы и необязательную рутину",
    create: "Создать расписание",
    save: "Сохранить замену",
    retry: "Повторить тот же запрос",
    cancel: "Отмена",
    archive_title: "Архивировать расписание?",
    reason: "Причина архивации",
    confirm_archive: "Я проверил(а) расписание и хочу отправить его в архив",
    history: "История",
    action_created: "Создано",
    action_updated: "Изменено",
    action_archived: "Архивировано",
    status_active: "Активно",
    status_archived: "В архиве",
    readonly: "Только чтение",
    unknown_member: "Участник семьи",
    none: "Нет",
    invalid:
      "Проверьте ребёнка, даты, уроки, пересечения, материалы и связанную рутину.",
    monday: "Понедельник",
    tuesday: "Вторник",
    wednesday: "Среда",
    thursday: "Четверг",
    friday: "Пятница",
    saturday: "Суббота",
    sunday: "Воскресенье",
  },
  uk: {
    title: "Шкільний розклад",
    help: "Батьки ведуть щотижневий розклад уроків і матеріалів. Дитина бачить лише свій найближчий шкільний порядок денний.",
    timezone: "Часовий пояс родини",
    upcoming: "Найближчі 14 днів",
    no_upcoming: "У цьому періоді немає майбутніх уроків.",
    timetables: "Розклади",
    no_timetables: "Розкладів поки немає.",
    new_timetable: "Новий розклад",
    edit: "Змінити розклад",
    archive: "Архівувати розклад",
    member: "Дитина",
    timetable_title: "Назва розкладу",
    valid_from: "Діє від",
    valid_until: "Діє до (необов’язково)",
    exceptions: "Дати без уроків",
    exceptions_hint: "Одна дата РРРР-ММ-ДД на рядок у межах періоду розкладу.",
    lessons: "Уроки тижня",
    add_lesson: "Додати урок",
    remove_lesson: "Видалити урок",
    weekday: "День тижня",
    start: "Початок",
    end: "Кінець",
    subject: "Предмет",
    room: "Кабінет (необов’язково)",
    materials: "Матеріали",
    materials_hint: "Одна позиція на рядок; до 12 для цього уроку.",
    backpack_routine: "Рутина складання рюкзака (необов’язково)",
    backpack_none: "Без пов’язаної рутини",
    backpack_unavailable: "Недоступна закріплена рутина",
    backpack_unavailable_hint:
      "Ця збережена версія рутини більше недоступна. Перед перевіркою явно виберіть варіант без рутини або поточну заміну.",
    revision: "версія",
    backpack_hint:
      "Обирається лише поточна версія шаблону. Це не запускає й не змінює рутину.",
    review: "Перевірити точний розклад",
    review_title: "Перевірка шкільного розкладу",
    confirm_save:
      "Я перевірив(ла) дитину, дати, усі уроки, матеріали й необов’язкову рутину",
    create: "Створити розклад",
    save: "Зберегти заміну",
    retry: "Повторити той самий запит",
    cancel: "Скасувати",
    archive_title: "Архівувати розклад?",
    reason: "Причина архівації",
    confirm_archive:
      "Я перевірив(ла) розклад і хочу перемістити його до архіву",
    history: "Історія",
    action_created: "Створено",
    action_updated: "Змінено",
    action_archived: "Архівовано",
    status_active: "Активний",
    status_archived: "В архіві",
    readonly: "Лише читання",
    unknown_member: "Учасник родини",
    none: "Немає",
    invalid:
      "Перевірте дитину, дати, уроки, перетини, матеріали й пов’язану рутину.",
    monday: "Понеділок",
    tuesday: "Вівторок",
    wednesday: "Середа",
    thursday: "Четвер",
    friday: "П’ятниця",
    saturday: "Субота",
    sunday: "Неділя",
  },
};
