"""Build error catalogs from HA translations; --check is read-only for CI."""

import argparse
import json
import pprint
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "custom_components" / "family_assistant"


def generated():
    errors = {
        language: json.loads(
            (ROOT / "translations" / f"{language}.json").read_text(encoding="utf-8")
        )["options"]["error"]
        for language in ("en", "ru", "uk")
    }
    yield (
        ROOT / "frontend" / "errors.js",
        (
            "// Generated by tools/sync_locales.py; edit HA translation JSON instead.\n"
            + "export const ERRORS = "
            + json.dumps(errors, indent=2, ensure_ascii=False)
            + ";\n"
        ),
    )
    python_path = ROOT / "telegram" / "errors.py"
    source = (
        '"""Generated by tools/sync_locales.py; edit HA translation JSON instead."""\n\n'
        + "ERRORS = "
        + pprint.pformat(errors, width=85, sort_dicts=False)
        + "\n"
    )
    formatted = subprocess.run(  # noqa: S603 - fixed formatter/module, no user input
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", str(python_path), "-"],
        input=source,
        text=True,
        capture_output=True,
        check=True,
        encoding="utf-8",
    ).stdout
    yield python_path, formatted


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in generated():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.name)
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Outdated generated catalogs: " + ", ".join(stale))
